package ai.jolli.jollimemory.core

import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import org.junit.jupiter.api.Test

/**
 * Golden tests for the pure wiki renderers — mirrors
 * `cli/src/core/WikiMarkdownBuilder.test.ts` so the Kotlin port stays
 * byte-compatible with the TS output.
 */
class WikiMarkdownBuilderTest {

    private val nullCtx = WikiRenderContext(
        repoName = "jolliai",
        resolveCommitVisiblePath = { null },
        resolveBranchFolder = { null },
        resolveCommitMessage = { null },
    )

    private val baseTopic = CompiledTopic(title = "Auth", stableSlug = "auth", content = "Body about auth.")

    @Test
    fun `renderTopicImpl renders the full document byte-for-byte`() {
        val md = renderTopicImpl(baseTopic, listOf("main"), "2026-01-01T00:00:00Z", nullCtx)
        val expected = listOf(
            "# Auth",
            "",
            "<!-- Generated by Jolli Memory · do not edit — regenerated on every merge -->",
            "",
            "> **Source branches:** main",
            "> **Merged:** 2026-01-01T00:00:00Z",
            "> **Topic slug:** `auth` (stable across re-merges)",
            "",
            "Body about auth.",
            "",
        ).joinToString("\n")
        md shouldBe expected
    }

    @Test
    fun `renderTopicImpl renders Key Decisions when present and omits when empty`() {
        val withDecisions = baseTopic.copy(keyDecisions = listOf("Use OAuth", "Drop sessions"))
        val md = renderTopicImpl(withDecisions, listOf("main"), "2026-01-01T00:00:00Z", nullCtx)
        md shouldContain "## Key Decisions"
        md shouldContain "- Use OAuth"
        md shouldContain "- Drop sessions"

        val empty = renderTopicImpl(baseTopic.copy(keyDecisions = emptyList()), listOf("main"), "t", nullCtx)
        empty shouldNotContain "## Key Decisions"
    }

    @Test
    fun `Source Commits falls back to hash + message when path unresolved`() {
        val ctx = nullCtx.copy(resolveCommitMessage = { h -> "commit $h" })
        val topic = baseTopic.copy(sourceCommits = listOf("abc12345deadbeef"))
        val md = renderTopicImpl(topic, listOf("main"), "t", ctx)
        md shouldContain "## Source Commits"
        md shouldContain "- `abc12345` — commit abc12345"
        md shouldNotContain "]("
    }

    @Test
    fun `Source Commits falls back to a bare hash when nothing resolves`() {
        val topic = baseTopic.copy(sourceCommits = listOf("abc12345deadbeef"))
        val md = renderTopicImpl(topic, listOf("main"), "t", nullCtx)
        md shouldContain "- `abc12345`"
        md shouldNotContain "`abc12345` —"
        md shouldNotContain "]("
    }

    @Test
    fun `Source Commits renders a relative link when path and message resolve`() {
        val ctx = nullCtx.copy(
            resolveCommitVisiblePath = { "../feature-oauth/summary--add-auth-abc12345.md" },
            resolveCommitMessage = { "Add auth" },
        )
        val topic = baseTopic.copy(sourceCommits = listOf("abc12345deadbeef"))
        val md = renderTopicImpl(topic, listOf("main"), "t", ctx)
        md shouldContain "- [abc12345](../feature-oauth/summary--add-auth-abc12345.md) — Add auth"
    }

    @Test
    fun `Related Branches links when folder resolves and falls back otherwise`() {
        val topic = baseTopic.copy(relatedBranches = listOf("feature/oauth"))
        val resolved = renderTopicImpl(
            topic, listOf("main"), "t",
            nullCtx.copy(resolveBranchFolder = { "feature-oauth" }),
        )
        resolved shouldContain "- [feature/oauth](../feature-oauth/)"

        val unresolved = renderTopicImpl(topic, listOf("main"), "t", nullCtx)
        unresolved shouldContain "- `feature/oauth`"
    }

    @Test
    fun `renderTopicKBIndex lists topics with relative links`() {
        val topics = listOf(
            CompiledTopic(title = "Auth", stableSlug = "auth", content = ""),
            CompiledTopic(title = "Sync", stableSlug = "sync", content = ""),
        )
        val expected = listOf(
            "# jolliai · Knowledge Wiki",
            "",
            "<!-- Generated by Jolli Memory · do not edit — regenerated on every merge -->",
            "",
            "> **2 topics** in the knowledge base",
            "",
            "## Topics",
            "",
            "- [Auth](topic--auth.md)",
            "- [Sync](topic--sync.md)",
            "",
        ).joinToString("\n")
        renderTopicKBIndex(topics, nullCtx) shouldBe expected
    }

    @Test
    fun `renderTopicKBIndex omits Topics section when empty`() {
        renderTopicKBIndex(emptyList(), nullCtx) shouldNotContain "## Topics"
    }

    @Test
    fun `mdLink escaping percent-encodes the target and escapes label brackets`() {
        // Brackets in a title are escaped; spaces/parens in the target are encoded.
        val topic = CompiledTopic(title = "A [x] (y)", stableSlug = "a", content = "")
        val md = renderTopicKBIndex(listOf(topic), nullCtx)
        md shouldContain "- [A \\[x\\] (y)](topic--a.md)"
    }

    @Test
    fun `topicPageToCompiledTopic maps summary refs to source commits and drops empty branches`() {
        val page = TopicPage(
            stableSlug = "auth",
            title = "Auth",
            content = "c",
            relatedBranches = emptyList(),
            sourceRefs = listOf(
                SourceRef("summary", "hash1", "t"),
                SourceRef("plan", "plan-slug", "t"),
                SourceRef("summary", "hash2", "t"),
            ),
            lastUpdatedAt = "t",
        )
        val compiled = topicPageToCompiledTopic(page)
        compiled.sourceCommits shouldBe listOf("hash1", "hash2")
        compiled.relatedBranches shouldBe null
    }
}
