/**
 * SummaryMarkdownBuilder
 *
 * Builds a Markdown string from a CommitSummary for clipboard export,
 * Jolli Space publishing, and file-based knowledge export.
 * Structure mirrors the webview layout.
 */

import type { CommitSummary, E2eTestScenario, ReferenceCommitRef, SourceId } from "../Types.js";
import { escMdLinkText, escMdUrl } from "./MarkdownEscape.js";
import {
	collectSortedTopics,
	formatDate,
	formatFullDate,
	formatProviderLabel,
	getDisplayDate,
	padIndex,
	type TopicWithDate,
} from "./SummaryFormat.js";
import { aggregateTurns, formatDurationLabel, resolveDiffStats } from "./SummaryTree.js";

/**
 * Builds a Markdown string from a CommitSummary for clipboard export.
 *
 * Structure mirrors the webview layout:
 * - H1: commit message
 * - Properties table: Commit, Branch, Author, Date, Changes
 * - Source Commits list (only for squash/multi-record summaries)
 * - Memories: numbered, each field rendered as a blockquote callout
 * - Footer: "Generated by Jolli Memory"
 */
export function buildMarkdown(summary: CommitSummary): string {
	const { topics: allTopics, sourceNodes } = collectSortedTopics(summary);
	const lines: Array<string> = [];

	pushPropertiesSection(lines, summary);
	pushPlansAndNotesSection(lines, summary);
	pushRecapSection(lines, summary);
	pushE2eTestSection(lines, summary.e2eTestGuide);
	pushSourceCommitsSection(lines, sourceNodes);
	pushTopicsSection(lines, allTopics, pushTopicBody);
	pushFooter(lines);

	return lines.join("\n");
}

// ── Shared section helpers ──────────────────────────────────────────────────

/** Appends the commit properties header (H1, metadata list, separator). */
export function pushPropertiesSection(lines: Array<string>, summary: CommitSummary): void {
	const displayStats = resolveDiffStats(summary);
	const totalFiles = displayStats.filesChanged;
	const totalTurns = aggregateTurns(summary);

	const filesLabel = `${totalFiles} file${totalFiles !== 1 ? "s" : ""} changed, +${displayStats.insertions} insertions, \u2212${displayStats.deletions} deletions`;
	const dateLabel = formatFullDate(getDisplayDate(summary));

	lines.push(
		`# ${summary.commitMessage}`,
		"",
		`- **Commit:** \`${summary.commitHash}\``,
		`- **Branch:** \`${summary.branch}\``,
		`- **Author:** ${summary.commitAuthor}`,
		`- **Date:** ${dateLabel}`,
		`- **Duration:** ${formatDurationLabel(summary)}`,
		`- **Changes:** ${filesLabel}`,
	);

	if (totalTurns > 0) {
		lines.push(`- **Conversations:** ${totalTurns} turn${totalTurns !== 1 ? "s" : ""}`);
	}

	const memoryDocUrl = summary.jolliDocUrl;
	if (memoryDocUrl) {
		lines.push(`- **Jolli Memory:** [${memoryDocUrl}](${memoryDocUrl})`);
	}

	lines.push("", "---");
}

/**
 * Appends a Quick recap section just below Plans & Notes (and above E2E Test
 * Guide). Skipped when the summary has no recap — keeps the section "present
 * iff content" semantics consistent with the Hoist family.
 */
export function pushRecapSection(lines: Array<string>, summary: CommitSummary): void {
	const recap = summary.recap?.trim();
	if (!recap) return;
	lines.push("", "## Quick recap", "", recap, "", "---");
}

const REFERENCE_SOURCE_ORDER: ReadonlyArray<SourceId> = ["linear", "jira", "github", "notion"];

/**
 * Returns references ordered by source (linear → jira → github → notion),
 * preserving within-source order, so the section reads deterministically
 * across regenerations.
 */
export function referencesBySourceOrder(
	references: ReadonlyArray<ReferenceCommitRef>,
): ReadonlyArray<ReferenceCommitRef> {
	const bySource = new Map<SourceId, Array<ReferenceCommitRef>>();
	for (const e of references) {
		const arr = bySource.get(e.source) ?? [];
		arr.push(e);
		bySource.set(e.source, arr);
	}
	const out: Array<ReferenceCommitRef> = [];
	for (const source of REFERENCE_SOURCE_ORDER) {
		const arr = bySource.get(source);
		if (arr) out.push(...arr);
	}
	return out;
}

/**
 * Appends a combined Plans & Notes section — title + URL for each item.
 * External references (Linear/Jira/GitHub/Notion) are rendered only when
 * `opts.includeReferences` is set — the PR path opts in; the clipboard/folder
 * path leaves it off, so the *references* output is the only part that differs
 * between the two paths (plan/note titles are escaped on both). Exported so PR
 * builders reuse it.
 */
export function pushPlansAndNotesSection(
	lines: Array<string>,
	summary: CommitSummary,
	opts?: { includeReferences?: boolean },
): void {
	const plans = summary.plans ?? [];
	const notes = summary.notes ?? [];
	const references: ReadonlyArray<ReferenceCommitRef> = opts?.includeReferences ? (summary.references ?? []) : [];
	const totalCount = plans.length + notes.length + references.length;
	if (totalCount === 0) {
		return;
	}
	const countLabel = totalCount > 1 ? ` (${totalCount})` : "";
	lines.push("", `## Context${countLabel}`, "");

	for (const plan of plans) {
		const planUrl = plan.jolliPlanDocUrl;
		lines.push(
			planUrl ? `- [${escMdLinkText(plan.title)}](${escMdUrl(planUrl)})` : `- ${escMdLinkText(plan.title)}`,
		);
	}

	for (const note of notes) {
		const noteUrl = note.jolliNoteDocUrl;
		lines.push(
			noteUrl ? `- [${escMdLinkText(note.title)}](${escMdUrl(noteUrl)})` : `- ${escMdLinkText(note.title)}`,
		);
	}

	for (const e of referencesBySourceOrder(references)) {
		lines.push(`- [${escMdLinkText(e.nativeId)} — ${escMdLinkText(e.title)}](${escMdUrl(e.url)})`);
	}
}

/** Appends the E2E test guide section (shared between clipboard and PR markdown). */
export function pushE2eTestSection(
	lines: Array<string>,
	e2eTestGuide: ReadonlyArray<E2eTestScenario> | undefined,
): void {
	if (!e2eTestGuide || e2eTestGuide.length === 0) {
		return;
	}
	lines.push("", `## E2E Test (${e2eTestGuide.length})`);
	for (let i = 0; i < e2eTestGuide.length; i++) {
		const s = e2eTestGuide[i];
		lines.push("", `### ${i + 1}. ${s.title}`);
		if (s.preconditions) {
			lines.push("", `**Preconditions:** ${s.preconditions}`);
		}
		lines.push("", "**Steps:**");
		for (let j = 0; j < s.steps.length; j++) {
			lines.push(`${j + 1}. ${s.steps[j]}`);
		}
		lines.push("", "**Expected Results:**");
		for (const r of s.expectedResults) {
			lines.push(`- ${r}`);
		}
	}
	lines.push("", "---");
}

/** Appends the source commits section (only for squash/multi-record summaries). */
export function pushSourceCommitsSection(lines: Array<string>, sourceNodes: ReadonlyArray<CommitSummary>): void {
	if (sourceNodes.length <= 1) {
		return;
	}
	lines.push("", `## Source Commits (${sourceNodes.length})`);
	for (const node of sourceNodes) {
		const nodeStats = resolveDiffStats(node);
		const turnsMd = node.conversationTurns ? ` · ${node.conversationTurns} turns` : "";
		lines.push(
			`- \`${node.commitHash.substring(0, 8)}\` ${node.commitMessage}  _(+${nodeStats.insertions} \u2212${nodeStats.deletions}${turnsMd} · ${formatDate(getDisplayDate(node))})_`,
		);
	}
	lines.push("", "---");
}

/** Appends the full topic body fields (trigger, decisions, response, todo, files). */
export function pushTopicBody(out: Array<string>, t: TopicWithDate): void {
	out.push("", "**⚡ Why This Change**", "", t.trigger);
	out.push("", "**💡 Decisions Behind the Code**", "", t.decisions);
	out.push("", "**✅ What Was Implemented**", "", t.response);
	if (t.todo) {
		out.push("", "**📋 Future Enhancements**", "", t.todo);
	}
	if (t.filesAffected && t.filesAffected.length > 0) {
		out.push("", "**📁 FILES**");
		for (const f of t.filesAffected) {
			out.push(`- \`${f}\``);
		}
	}
}

/**
 * Appends the memories/summaries section. Flat list. The section heading label
 * defaults to "Summary"/"Summaries" (clipboard/folder export); the push path
 * passes `{ singular: "Topic", plural: "Topics" }` so pushed docs read as
 * "Topic(s)" without duplicating the whole section builder.
 */
export function pushTopicsSection(
	lines: Array<string>,
	allTopics: Array<TopicWithDate>,
	bodyFn: (out: Array<string>, t: TopicWithDate) => void,
	label: { singular: string; plural: string } = { singular: "Summary", plural: "Summaries" },
): void {
	if (allTopics.length === 0) {
		return;
	}
	lines.push("", `## ${allTopics.length === 1 ? label.singular : label.plural} (${allTopics.length})`);
	for (let i = 0; i < allTopics.length; i++) {
		const t = allTopics[i];
		const catLabel = t.category ? ` \`${t.category}\`` : "";
		lines.push("", `### ${padIndex(i)} · ${t.title}${catLabel}`);
		bodyFn(lines, t);
	}
}

/**
 * Appends the standard "Generated by Jolli Memory" footer. When `summary`
 * carries provider attribution (`llm.source`) it is appended as
 * `· via <provider>`. Clipboard/folder callers pass no `summary`, preserving
 * the original two-segment footer. Exported so the PR builders reuse it.
 */
export function pushFooter(lines: Array<string>, summary?: CommitSummary): void {
	const generatedAt = formatFullDate(new Date().toISOString());
	const provider = summary ? formatProviderLabel(summary) : undefined;
	const tail = provider ? ` · via ${provider}` : "";
	lines.push("", "---", "", `*Generated by Jolli Memory · ${generatedAt}${tail}*`);
}
