/**
 * SummaryMarkdownBuilder
 *
 * Builds a Markdown string from a CommitSummary for clipboard export,
 * Jolli Space publishing, and file-based knowledge export.
 * Structure mirrors the webview layout.
 */

import type { CommitSummary, E2eTestScenario } from "../Types.js";
import {
	collectSortedTopics,
	formatDate,
	formatFullDate,
	getDisplayDate,
	padIndex,
	type TopicWithDate,
} from "./SummaryFormat.js";
import { aggregateTurns, formatDurationLabel, resolveDiffStats } from "./SummaryTree.js";

/**
 * Builds a Markdown string from a CommitSummary for clipboard export.
 *
 * Structure mirrors the webview layout:
 * - H1: commit message
 * - Properties table: Commit, Branch, Author, Date, Changes
 * - Source Commits list (only for squash/multi-record summaries)
 * - Memories: numbered, each field rendered as a blockquote callout
 * - Footer: "Generated by Jolli Memory"
 */
export function buildMarkdown(summary: CommitSummary): string {
	const { topics: allTopics, sourceNodes } = collectSortedTopics(summary);
	const lines: Array<string> = [];

	pushPropertiesSection(lines, summary);
	pushPlansAndNotesSection(lines, summary);
	pushRecapSection(lines, summary);
	pushE2eTestSection(lines, summary.e2eTestGuide);
	pushSourceCommitsSection(lines, sourceNodes);
	pushTopicsSection(lines, allTopics, pushTopicBody);
	pushFooter(lines);

	return lines.join("\n");
}

/**
 * Builds a simplified Markdown string optimized for GitHub PR descriptions.
 *
 * Only includes information not already visible on the PR page:
 * - Jolli Memory URL (if pushed)
 * - Associated Plans with URLs
 * - E2E Test Guide
 * - Summaries: Why (trigger) -> Decisions -> What (response)
 * - Footer
 */
export function buildPrMarkdown(summary: CommitSummary): string {
	const { topics: allTopics } = collectSortedTopics(summary);
	const lines: Array<string> = [];

	// Jolli Memory URL
	const memoryDocUrl = summary.jolliDocUrl;
	if (memoryDocUrl) {
		lines.push("", "## Jolli Memory", "", `${memoryDocUrl}`);
	}

	pushPlansAndNotesSection(lines, summary);
	pushRecapSection(lines, summary);
	pushE2eTestSection(lines, summary.e2eTestGuide);
	pushPrTopicsSection(lines, allTopics);
	pushFooter(lines);

	return lines.join("\n");
}

// ── Shared section helpers ──────────────────────────────────────────────────

/** Appends the commit properties header (H1, metadata list, separator). */
function pushPropertiesSection(lines: Array<string>, summary: CommitSummary): void {
	const displayStats = resolveDiffStats(summary);
	const totalFiles = displayStats.filesChanged;
	const totalTurns = aggregateTurns(summary);

	const filesLabel = `${totalFiles} file${totalFiles !== 1 ? "s" : ""} changed, +${displayStats.insertions} insertions, \u2212${displayStats.deletions} deletions`;
	const dateLabel = formatFullDate(getDisplayDate(summary));

	lines.push(
		`# ${summary.commitMessage}`,
		"",
		`- **Commit:** \`${summary.commitHash}\``,
		`- **Branch:** \`${summary.branch}\``,
		`- **Author:** ${summary.commitAuthor}`,
		`- **Date:** ${dateLabel}`,
		`- **Duration:** ${formatDurationLabel(summary)}`,
		`- **Changes:** ${filesLabel}`,
	);

	if (totalTurns > 0) {
		lines.push(`- **Conversations:** ${totalTurns} turn${totalTurns !== 1 ? "s" : ""}`);
	}

	const memoryDocUrl = summary.jolliDocUrl;
	if (memoryDocUrl) {
		lines.push(`- **Jolli Memory:** [${memoryDocUrl}](${memoryDocUrl})`);
	}

	lines.push("", "---");
}

/**
 * Appends a Quick recap section just below Plans & Notes (and above E2E Test
 * Guide). Skipped when the summary has no recap — keeps the section "present
 * iff content" semantics consistent with the Hoist family.
 */
function pushRecapSection(lines: Array<string>, summary: CommitSummary): void {
	const recap = summary.recap?.trim();
	if (!recap) return;
	lines.push("", "## Quick recap", "", recap, "", "---");
}

/** Appends a combined Plans & Notes section — title + URL for each item. */
function pushPlansAndNotesSection(lines: Array<string>, summary: CommitSummary): void {
	const plans = summary.plans ?? [];
	const notes = summary.notes ?? [];
	const totalCount = plans.length + notes.length;
	if (totalCount === 0) {
		return;
	}
	const countLabel = totalCount > 1 ? ` (${totalCount})` : "";
	lines.push("", `## Plans & Notes${countLabel}`, "");

	for (const plan of plans) {
		const planUrl = plan.jolliPlanDocUrl;
		lines.push(planUrl ? `- [${plan.title}](${planUrl})` : `- ${plan.title}`);
	}

	for (const note of notes) {
		const noteUrl = note.jolliNoteDocUrl;
		lines.push(noteUrl ? `- [${note.title}](${noteUrl})` : `- ${note.title}`);
	}
}

/** Appends the E2E test guide section (shared between clipboard and PR markdown). */
function pushE2eTestSection(lines: Array<string>, e2eTestGuide: ReadonlyArray<E2eTestScenario> | undefined): void {
	if (!e2eTestGuide || e2eTestGuide.length === 0) {
		return;
	}
	lines.push("", `## E2E Test (${e2eTestGuide.length})`);
	for (let i = 0; i < e2eTestGuide.length; i++) {
		const s = e2eTestGuide[i];
		lines.push("", `### ${i + 1}. ${s.title}`);
		if (s.preconditions) {
			lines.push("", `**Preconditions:** ${s.preconditions}`);
		}
		lines.push("", "**Steps:**");
		for (let j = 0; j < s.steps.length; j++) {
			lines.push(`${j + 1}. ${s.steps[j]}`);
		}
		lines.push("", "**Expected Results:**");
		for (const r of s.expectedResults) {
			lines.push(`- ${r}`);
		}
	}
	lines.push("", "---");
}

/** Appends the source commits section (only for squash/multi-record summaries). */
function pushSourceCommitsSection(lines: Array<string>, sourceNodes: ReadonlyArray<CommitSummary>): void {
	if (sourceNodes.length <= 1) {
		return;
	}
	lines.push("", `## Source Commits (${sourceNodes.length})`);
	for (const node of sourceNodes) {
		const nodeStats = resolveDiffStats(node);
		const turnsMd = node.conversationTurns ? ` · ${node.conversationTurns} turns` : "";
		lines.push(
			`- \`${node.commitHash.substring(0, 8)}\` ${node.commitMessage}  _(+${nodeStats.insertions} \u2212${nodeStats.deletions}${turnsMd} · ${formatDate(getDisplayDate(node))})_`,
		);
	}
	lines.push("", "---");
}

/** Appends the full topic body fields (trigger, decisions, response, todo, files). */
function pushTopicBody(out: Array<string>, t: TopicWithDate): void {
	out.push("", "**⚡ Why This Change**", "", t.trigger);
	out.push("", "**💡 Decisions Behind the Code**", "", t.decisions);
	out.push("", "**✅ What Was Implemented**", "", t.response);
	if (t.todo) {
		out.push("", "**📋 Future Enhancements**", "", t.todo);
	}
	if (t.filesAffected && t.filesAffected.length > 0) {
		out.push("", "**📁 FILES**");
		for (const f of t.filesAffected) {
			out.push(`- \`${f}\``);
		}
	}
}

/** Appends simplified topic body for PR: trigger, decisions, response (no todo/files). */
function pushPrTopicBody(out: Array<string>, t: TopicWithDate): void {
	out.push("", "**⚡ Why This Change**", "", t.trigger);
	out.push("", "**💡 Decisions Behind the Code**", "", t.decisions);
	out.push("", "**✅ What Was Implemented**", "", t.response);
}

/** Appends the memories/summaries section for clipboard export. Flat list. */
function pushTopicsSection(
	lines: Array<string>,
	allTopics: Array<TopicWithDate>,
	bodyFn: (out: Array<string>, t: TopicWithDate) => void,
): void {
	if (allTopics.length === 0) {
		return;
	}
	lines.push("", `## ${allTopics.length === 1 ? "Summary" : "Summaries"} (${allTopics.length})`);
	for (let i = 0; i < allTopics.length; i++) {
		const t = allTopics[i];
		const catLabel = t.category ? ` \`${t.category}\`` : "";
		lines.push("", `### ${padIndex(i)} · ${t.title}${catLabel}`);
		bodyFn(lines, t);
	}
}

/**
 * Appends the PR summaries section with GitHub body-size truncation.
 * Uses simplified topic body (no todo/files) and stops adding topics
 * once the PR body would exceed the GitHub character limit.
 */
function pushPrTopicsSection(lines: Array<string>, allTopics: Array<TopicWithDate>): void {
	if (allTopics.length === 0) {
		return;
	}

	// GitHub PR body limit is 65536 chars. Reserve space for footer + markers (~200 chars).
	const PR_BODY_LIMIT = 65000;

	lines.push("", `## ${allTopics.length === 1 ? "Summary" : "Summaries"} (${allTopics.length})`);
	let includedCount = 0;
	const currentLength = () => lines.join("\n").length;

	for (let i = 0; i < allTopics.length; i++) {
		const topicLines: Array<string> = [];
		topicLines.push("", `### ${padIndex(i)} · ${allTopics[i].title}`);
		pushPrTopicBody(topicLines, allTopics[i]);
		if (currentLength() + topicLines.join("\n").length > PR_BODY_LIMIT) {
			break;
		}
		lines.push(...topicLines);
		includedCount++;
	}

	const omitted = allTopics.length - includedCount;
	if (omitted > 0) {
		lines.push(
			"",
			`> ⚠️ ${omitted} more summar${omitted !== 1 ? "ies" : "y"} omitted due to GitHub PR body size limit.`,
		);
	}
}

/** Appends the standard "Generated by Jolli Memory" footer. */
function pushFooter(lines: Array<string>): void {
	const generatedAt = formatFullDate(new Date().toISOString());
	lines.push("", "---", "", `*Generated by Jolli Memory · ${generatedAt}*`);
}
