/**
 * SummaryMarkdownBuilder
 *
 * Builds a Markdown string from a CommitSummary for clipboard export,
 * Jolli Space publishing, and file-based knowledge export.
 * Structure mirrors the webview layout.
 */

import type { CommitSummary, E2eTestScenario, ReferenceCommitRef, SkillCommitRef, SourceId } from "../Types.js";
import { escMdLinkText, escMdStrikeText, escMdUrl } from "./MarkdownEscape.js";
import { REF_HASH_SUFFIX } from "./RefMerge.js";
import { referenceDisplayTitle } from "./references/ReferenceDisplay.js";
import { getRegistry } from "./references/SourceDefinitionRegistry.js";
import { buildSkillsSummaryLabel, buildSkillsTable } from "./SkillsAggregateMarkdown.js";
import {
	collectSortedTopics,
	formatDate,
	formatFullDate,
	formatProviderLabel,
	getDisplayDate,
	padIndex,
	skillSourceLabel,
	type TopicWithDate,
} from "./SummaryFormat.js";
import {
	aggregateConversationTokenBreakdown,
	aggregateConversationTokens,
	aggregateTurns,
	formatDurationLabel,
	resolveDiffStats,
} from "./SummaryTree.js";
import { estimateConversationCostUsd, formatExactCostUsd, formatTokensExact } from "./TokenCost.js";

/**
 * Builds a Markdown string from a CommitSummary for clipboard export.
 *
 * Structure mirrors the webview layout:
 * - H1: commit message
 * - Properties table: Commit, Branch, Author, Date, Changes
 * - Source Commits list (only for squash/multi-record summaries)
 * - Memories: numbered, each field rendered as a blockquote callout
 * - Footer: "Generated by Jolli Memory"
 */
export function buildMarkdown(summary: CommitSummary): string {
	const { topics: allTopics, sourceNodes } = collectSortedTopics(summary);
	const lines: Array<string> = [];

	pushPropertiesSection(lines, summary);
	// withRelevance: the memory/summary export shows the AI relevance picture —
	// per-item tier+reason on kept rows plus the AI-excluded items inlined as
	// read-only rows. PR builders call pushPlansAndNotesSection WITHOUT the flag
	// so PR bodies keep their original, relevance-free Context section.
	pushPlansAndNotesSection(lines, summary, { withRelevance: true });
	pushRecapSection(lines, summary);
	pushE2eTestSection(lines, summary.e2eTestGuide);
	pushSourceCommitsSection(lines, sourceNodes);
	pushTopicsSection(lines, allTopics, pushTopicBody);
	pushFooter(lines);

	return lines.join("\n");
}

// ── Shared section helpers ──────────────────────────────────────────────────

/** Appends the commit properties header (H1, metadata list, separator). */
export function pushPropertiesSection(lines: Array<string>, summary: CommitSummary): void {
	const displayStats = resolveDiffStats(summary);
	const totalFiles = displayStats.filesChanged;
	const totalTurns = aggregateTurns(summary);

	const filesLabel = `${totalFiles} file${totalFiles !== 1 ? "s" : ""} changed, +${displayStats.insertions} insertions, \u2212${displayStats.deletions} deletions`;
	const dateLabel = formatFullDate(getDisplayDate(summary));

	lines.push(
		`# ${summary.commitMessage}`,
		"",
		`- **Commit:** \`${summary.commitHash}\``,
		`- **Branch:** \`${summary.branch}\``,
		`- **Author:** ${summary.commitAuthor}`,
		`- **Date:** ${dateLabel}`,
		`- **Duration:** ${formatDurationLabel(summary)}`,
		`- **Changes:** ${filesLabel}`,
	);

	if (totalTurns > 0) {
		lines.push(`- **Conversations:** ${totalTurns} turn${totalTurns !== 1 ? "s" : ""}`);
	}

	// Task usage: token total + cache-aware cost estimate, aggregated across the
	// whole consolidation tree (a squash/amend memory carries its tokens on folded
	// children). Three states mirror the VS Code token meter; omit-when-zero matches
	// the Conversations line above (no "not reported" state in a property list).
	// The article shows EXACT figures (thousands-separated counts, precise $) rather
	// than the compact form the space-constrained UI token bar uses.
	const totalTokens = aggregateConversationTokens(summary);
	if (totalTokens > 0) {
		const agg = aggregateConversationTokenBreakdown(summary);
		const b = agg.input > 0 || agg.output > 0 || agg.cached > 0 ? agg : undefined;
		const cost = formatExactCostUsd(estimateConversationCostUsd(b, totalTokens));
		const split = b
			? ` (${formatTokensExact(b.input)} input, ${formatTokensExact(b.output)} output, ${formatTokensExact(b.cached)} cached)`
			: "";
		lines.push(`- **Task usage:** ${formatTokensExact(totalTokens)} tokens · ${cost}${split}`);
	}

	const memoryDocUrl = summary.jolliDocUrl;
	if (memoryDocUrl) {
		lines.push(`- **Jolli Memory:** [${memoryDocUrl}](${memoryDocUrl})`);
	}

	lines.push("", "---");
}

/**
 * Appends a Quick recap section just below Plans & Notes (and above E2E Test
 * Guide). Skipped when the summary has no recap — keeps the section "present
 * iff content" semantics consistent with the Hoist family.
 */
export function pushRecapSection(lines: Array<string>, summary: CommitSummary): void {
	const recap = summary.recap?.trim();
	if (!recap) return;
	lines.push("", "## Quick recap", "", recap, "", "---");
}

/**
 * Returns references ordered by source (registration order in
 * `SourceDefinitionRegistry` — linear → jira → github → notion for the 4
 * built-ins), preserving within-source order, so the section reads
 * deterministically across regenerations.
 *
 * A `source` not currently registered (e.g. a definition removed after a repo
 * already has references archived under it) is appended after the known
 * sources, in first-seen order, rather than silently dropped.
 */
export function referencesBySourceOrder(
	references: ReadonlyArray<ReferenceCommitRef>,
): ReadonlyArray<ReferenceCommitRef> {
	const bySource = new Map<SourceId, Array<ReferenceCommitRef>>();
	for (const e of references) {
		const arr = bySource.get(e.source) ?? [];
		arr.push(e);
		bySource.set(e.source, arr);
	}
	const knownOrder = getRegistry()
		.all()
		.map((d) => d.id);
	const out: Array<ReferenceCommitRef> = [];
	for (const source of knownOrder) {
		const arr = bySource.get(source);
		if (arr) {
			out.push(...arr);
			bySource.delete(source);
		}
	}
	for (const arr of bySource.values()) out.push(...arr);
	return out;
}

/** Relevance lookup for one archived ref: exact key first (covers unarchived or
 *  naturally-hex-ending working keys), then the archive-suffix-stripped base.
 *  `REF_HASH_SUFFIX` (from RefMerge) is the archive suffix on committed plan slugs
 *  / note ids (`slug-<hash8>`); relevance keys are working-area identities, i.e.
 *  pre-archive, which is why the stripped form has to be tried at all. */
function lookupRelevance(
	map: ReadonlyMap<string, { tier: "high" | "mid" | "low"; reason: string }>,
	kind: "plan" | "note" | "reference",
	key: string,
): { tier: "high" | "mid" | "low"; reason: string } | undefined {
	return map.get(`${kind}:${key}`) ?? map.get(`${kind}:${key.replace(REF_HASH_SUFFIX, "")}`);
}

const TIER_LABEL = { high: "High", mid: "Med", low: "Low" } as const;

/** ` — High · reason` suffix for a kept row; empty when the item has no verdict
 *  (legacy summaries, fail-open runs). An empty reason (fabricated fail-open
 *  verdict that slipped into an artifact) renders no suffix rather than a
 *  dangling `High · `. */
function relevanceSuffix(rel: { tier: "high" | "mid" | "low"; reason: string } | undefined): string {
	if (!rel || rel.reason === "") return "";
	return ` — ${TIER_LABEL[rel.tier]} · ${escMdLinkText(rel.reason)}`;
}

/**
 * Appends a combined Plans & Notes section — title + URL for each item.
 * External references (Linear/Jira/GitHub/Notion) are rendered only when
 * `opts.includeReferences` is set — the PR path opts in; the clipboard/folder
 * path leaves it off, so the *references* output is the only part that differs
 * between the two paths (plan/note titles are escaped on both). Exported so PR
 * builders reuse it.
 *
 * `opts.withRelevance` (memory/summary export only — PR builders leave it off)
 * additionally renders the AI relevance picture: each kept row gains a
 * ` — High/Med/Low · reason` suffix from `summary.contextRelevance`, and the
 * AI-excluded items (`summary.excludedContext`) are inlined as read-only rows
 * at the end (struck-through title + `Excluded` tag + reason, no links). This
 * replaced the old collapsed `<details>` block so kept and excluded items read
 * as one list.
 */
export function pushPlansAndNotesSection(
	lines: Array<string>,
	summary: CommitSummary,
	opts?: { includeReferences?: boolean; withRelevance?: boolean },
): void {
	const plans = summary.plans ?? [];
	const notes = summary.notes ?? [];
	const references: ReadonlyArray<ReferenceCommitRef> = opts?.includeReferences ? (summary.references ?? []) : [];
	const excluded = opts?.withRelevance ? (summary.excludedContext ?? []) : [];
	const relevanceMap = new Map<string, { tier: "high" | "mid" | "low"; reason: string }>();
	if (opts?.withRelevance) {
		for (const r of summary.contextRelevance ?? []) {
			relevanceMap.set(`${r.kind}:${r.key}`, { tier: r.tier, reason: r.reason });
		}
	}
	// Skills always render — they are not gated by `includeReferences`, which exists
	// to keep PR bodies free of external-tracker rows. A skill has no external
	// destination and no relevance verdict, so neither concern applies.
	const skills = summary.skills ?? [];
	// Skills contribute ONE to the count, however many were captured: they render as
	// a single aggregate row here, exactly as they do in every Context surface in the
	// UI. The per-skill breakdown lives in the commit's `skills--<hash8>.md`.
	const totalCount = plans.length + notes.length + references.length + (skills.length > 0 ? 1 : 0);
	if (totalCount === 0 && excluded.length === 0) {
		return;
	}
	const countLabel = totalCount > 1 ? ` (${totalCount})` : "";
	lines.push("", `## Context${countLabel}`, "");

	for (const plan of plans) {
		const planUrl = plan.jolliPlanDocUrl;
		const suffix = relevanceSuffix(lookupRelevance(relevanceMap, "plan", plan.slug));
		lines.push(
			(planUrl ? `- [${escMdLinkText(plan.title)}](${escMdUrl(planUrl)})` : `- ${escMdLinkText(plan.title)}`) +
				suffix,
		);
	}

	for (const note of notes) {
		const noteUrl = note.jolliNoteDocUrl;
		const suffix = relevanceSuffix(lookupRelevance(relevanceMap, "note", note.id));
		lines.push(
			(noteUrl ? `- [${escMdLinkText(note.title)}](${escMdUrl(noteUrl)})` : `- ${escMdLinkText(note.title)}`) +
				suffix,
		);
	}

	for (const e of referencesBySourceOrder(references)) {
		// Prefer the pushed Space article; fall back to the external link when the
		// reference hasn't been pushed (or the push failed) so the row is never dead.
		const label = escMdLinkText(referenceDisplayTitle(e));
		const target = e.jolliReferenceDocUrl ?? e.url;
		const suffix = relevanceSuffix(lookupRelevance(relevanceMap, "reference", `${e.source}:${e.nativeId}`));
		lines.push((target ? `- [${label}](${escMdUrl(target)})` : `- ${label}`) + suffix);
	}

	// Skills last among the kept rows: they describe HOW the work happened, while the
	// plans / notes / references above are what it was about. Never linked — a skill
	// invocation is a local act with no external destination to open, unlike every
	// other row here. No relevance suffix either: skills are never fed to the
	// relevance ranker, so a verdict for one cannot exist.
	//
	// ONE aggregate row, not one per skill. A session routinely enters a dozen
	// skills, which would bury the plans and notes this section exists to list; the
	// per-skill figures are in the commit's `skills--<hash8>.md`. Every Context
	// surface in the UI collapses them the same way, and this Markdown is what those
	// panels export.
	if (skills.length > 0) {
		// "inferred" is stated on the row, not in a footnote: this section is read
		// inline and a marker the reader has to look up would be missed.
		const inferred = skills.some((s) => s.detection === "heuristic") ? " · some inferred" : "";
		lines.push(`- Skills used — ${escMdLinkText(buildSkillsSummaryLabel(skills))}${inferred}`);
	}

	// AI-excluded items, inlined read-only after the kept rows: struck-through
	// title, an `Excluded` tag in place of a tier, and the AI's reason. No links
	// — a soft-excluded item was never archived into this commit, so there is
	// nothing to open. escMdStrikeText additionally escapes tildes so a literal
	// `~~` inside the title can't close the strikethrough early.
	for (const e of excluded) {
		lines.push(`- ~~${escMdStrikeText(e.title)}~~ — Excluded${e.reason ? ` · ${escMdLinkText(e.reason)}` : ""}`);
	}
}

/**
 * Builds the article body pushed for a single archived reference (docType
 * `reference`). The header — the external link, the originating tool, and the
 * source-specific `fields` as a table — is synthesized from the `ReferenceCommitRef`
 * value snapshot (native id + title become the article TITLE, see
 * `buildReferencePushTitle`, so they aren't repeated). `description` is the stored
 * markdown body (the issue/PR/page content) that the caller reads back from the
 * orphan-branch snapshot (`readReferenceFromBranch`) so the pushed article carries
 * the SAME body VS Code shows locally, rather than a thinner card. Omitted (header
 * only) when the snapshot has no body or can't be read.
 */
export function buildReferencePushMarkdown(ref: ReferenceCommitRef, description?: string): string {
	const lines: Array<string> = [];
	// `url` is optional (e.g. Slack references may carry none) — omit the row rather than emit a dead link.
	if (ref.url) {
		lines.push(`- **Link:** [${escMdLinkText(ref.url)}](${escMdUrl(ref.url)})`);
	}
	lines.push(`- **Source:** ${escMdLinkText(ref.sourceToolName)}`);
	const fields = ref.fields ?? [];
	if (fields.length > 0) {
		lines.push("", "| Field | Value |", "| --- | --- |");
		for (const f of fields) {
			// Escape backslashes first, then pipes, and normalize newlines so a field
			// value can't break the table layout (a trailing `\` must not turn the
			// escaped `\|` back into a literal cell separator).
			const cell = (s: string) => s.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
			lines.push(`| ${cell(f.label)} | ${cell(f.value)} |`);
		}
	}
	// The stored body (source content) below the header, matching the local reference
	// markdown VS Code renders. Trim edges so the render stays stable.
	const body = description?.replace(/^\n+/, "").replace(/\n+$/, "");
	if (body) {
		lines.push("", body);
	}
	return lines.join("\n");
}

/**
 * Builds the article body pushed for ONE COMMIT's whole skill aggregate (docType
 * `skill`).
 *
 * **One article per commit, listing every skill** — the same set, in the same
 * table, as the Memory Bank's `skills--<hash8>.md` and the single "Skills used"
 * Context row every IDE surface renders. It used to be one article per (skill,
 * commit), so a commit that entered six skills published six documents against a
 * local Context that shows exactly one file. The local aggregate is the shape the
 * user already reads; the push now matches it rather than inventing a second
 * decomposition of the same data.
 *
 * The table goes through {@link buildSkillsTable} — the same renderer the local
 * aggregate and the sidebar use, which owns the em-dash-not-zero rule, the `~`
 * estimate marker, the `†` inferred footnote and the heaviest-first ordering. That
 * is what keeps this body byte-identical to the table VS Code shows for the same
 * commit. Per-skill identity is split deliberately: host is promoted into the table
 * to disambiguate equal skill ids, while plugin and entry paths stay BELOW it as a
 * detail list.
 *
 * **Every figure is THIS COMMIT's increment, read off the refs alone.** That is
 * the whole contract of this function, and it is a deliberate reversal: the body
 * used to prefer the orphan-branch snapshot's frontmatter, whose counters are the
 * registry row's RUNNING TOTAL across every commit that used the skill (see
 * `SkillEntry.archivedTotals` and `foldSkillUse`'s accumulating
 * `invocationCount`). A reader comparing the article against the same record in
 * the VS Code panel — which renders `summary.skills` through
 * {@link buildSkillsAggregateMarkdown}, i.e. the increment — saw two different
 * numbers for one commit, and the article's were the larger, so the memory looked
 * more expensive than it was.
 *
 * Making the increment win is only coherent because the article is per COMMIT:
 * with the old cross-commit `baseKey` a single shared document would have shown
 * whichever commit pushed last. The two changes are one change — see the `skill`
 * definition's `baseKey` and `aggregate` in `push/kinds/index.ts`.
 *
 * **Three things the old body carried are deliberately gone**, all for the same
 * reason — they are cumulative and cannot be re-derived per commit, so in a
 * per-commit article each one contradicted the table beside it:
 *
 *   - `## Invocations`, the snapshot's verbatim per-invocation rows. Cumulative by
 *     construction (and capped), so it listed four entries under `Invocations: 1`.
 *     No VS Code surface shows it either — neither {@link buildSkillsAggregateMarkdown}
 *     nor `buildLiveSkillsMarkdown` renders invocation detail.
 *   - `First used` / `Last used`. `SkillArchive` stamps these from the registry
 *     ROW, not the delta, so they span the skill's whole life: an August commit's
 *     article read `First used: July 30`.
 *   - The `- **Invocations:** N` bullet, which the table's `×` column already
 *     states. Removing it means the count exists in exactly one place.
 *
 * `entryPaths` and `plugin` stay despite also being cumulative unions: they are
 * identity (HOW the skill is entered), not measurements, so they cannot be read as
 * overstating what this commit cost.
 */
export function buildSkillsPushMarkdown(refs: ReadonlyArray<SkillCommitRef>): string {
	// The token figures go through the SAME renderer every other skill surface
	// uses, rather than being re-formatted here: `buildSkillsTable` owns the
	// em-dash-not-zero rule, the `~` estimate marker, the `†` inferred footnote and
	// the heaviest-first ordering, and its docstring is explicit that those must not
	// be duplicated. Passing the refs straight through is what keeps this table
	// byte-identical to the one the VS Code panel renders for the same commit.
	const lines: Array<string> = [
		...buildSkillsTable(
			refs.map((ref) => ({
				skill: ref.skill,
				// Projected explicitly, like every other field here: this map picks fields
				// rather than spreading the ref, so a column added to the table renders as
				// an em dash in the pushed article until it is named here too.
				source: ref.source,
				invocationCount: ref.invocationCount,
				...(ref.usage !== undefined && { usage: ref.usage }),
				...(ref.detection !== undefined && { detection: ref.detection }),
			})),
		),
	];

	// The identity fields that are not columns stay below the table.
	// Ordered by skill id rather than by weight: this list is looked up by name, and
	// a stable order keeps a re-push from producing a spurious diff.
	const detailed = [...refs].sort((a, b) => (a.skill < b.skill ? -1 : a.skill > b.skill ? 1 : 0));
	const details: Array<string> = [];
	for (const ref of detailed) {
		const bits: Array<string> = [`Host: ${escMdLinkText(skillSourceLabel(ref.source))}`];
		if (ref.plugin !== undefined && ref.plugin !== "") {
			bits.push(`Plugin: ${escMdLinkText(ref.plugin)}`);
		}
		if (ref.entryPaths.length > 0) {
			bits.push(`Entered via: ${ref.entryPaths.map((p) => escMdLinkText(p)).join(", ")}`);
		}
		details.push(`- **${escMdLinkText(ref.skill)}** — ${bits.join(" · ")}`);
	}
	if (details.length > 0) {
		lines.push("", "## Skill details", "", ...details);
	}
	return lines.join("\n");
}

/** Appends the E2E test guide section (shared between clipboard and PR markdown). */
export function pushE2eTestSection(
	lines: Array<string>,
	e2eTestGuide: ReadonlyArray<E2eTestScenario> | undefined,
): void {
	if (!e2eTestGuide || e2eTestGuide.length === 0) {
		return;
	}
	lines.push("", `## E2E Test (${e2eTestGuide.length})`);
	for (let i = 0; i < e2eTestGuide.length; i++) {
		const s = e2eTestGuide[i];
		lines.push("", `### ${i + 1}. ${s.title}`);
		if (s.preconditions) {
			lines.push("", `**Preconditions:** ${s.preconditions}`);
		}
		lines.push("", "**Steps:**");
		for (let j = 0; j < s.steps.length; j++) {
			lines.push(`${j + 1}. ${s.steps[j]}`);
		}
		lines.push("", "**Expected Results:**");
		for (const r of s.expectedResults) {
			lines.push(`- ${r}`);
		}
	}
	lines.push("", "---");
}

/** Appends the source commits section (only for squash/multi-record summaries). */
export function pushSourceCommitsSection(lines: Array<string>, sourceNodes: ReadonlyArray<CommitSummary>): void {
	if (sourceNodes.length <= 1) {
		return;
	}
	lines.push("", `## Source Commits (${sourceNodes.length})`);
	for (const node of sourceNodes) {
		const nodeStats = resolveDiffStats(node);
		const turnsMd = node.conversationTurns ? ` · ${node.conversationTurns} turns` : "";
		lines.push(
			`- \`${node.commitHash.substring(0, 8)}\` ${node.commitMessage}  _(+${nodeStats.insertions} \u2212${nodeStats.deletions}${turnsMd} · ${formatDate(getDisplayDate(node))})_`,
		);
	}
	lines.push("", "---");
}

/** Appends the full topic body fields (trigger, decisions, response, todo, files). */
export function pushTopicBody(out: Array<string>, t: TopicWithDate): void {
	out.push("", "**⚡ Why This Change**", "", t.trigger);
	out.push("", "**💡 Decisions Behind the Code**", "", t.decisions);
	out.push("", "**✅ What Was Implemented**", "", t.response);
	if (t.todo) {
		out.push("", "**📋 Future Enhancements**", "", t.todo);
	}
	if (t.filesAffected && t.filesAffected.length > 0) {
		out.push("", "**📁 FILES**");
		for (const f of t.filesAffected) {
			out.push(`- \`${f}\``);
		}
	}
}

/**
 * Appends the memories/summaries section. Flat list. The section heading label
 * defaults to "Summary"/"Summaries" (clipboard/folder export); the push path
 * passes `{ singular: "Topic", plural: "Topics" }` so pushed docs read as
 * "Topic(s)" without duplicating the whole section builder.
 */
export function pushTopicsSection(
	lines: Array<string>,
	allTopics: Array<TopicWithDate>,
	bodyFn: (out: Array<string>, t: TopicWithDate) => void,
	label: { singular: string; plural: string } = { singular: "Summary", plural: "Summaries" },
): void {
	if (allTopics.length === 0) {
		return;
	}
	lines.push("", `## ${allTopics.length === 1 ? label.singular : label.plural} (${allTopics.length})`);
	for (let i = 0; i < allTopics.length; i++) {
		const t = allTopics[i];
		const catLabel = t.category ? ` \`${t.category}\`` : "";
		lines.push("", `### ${padIndex(i)} · ${t.title}${catLabel}`);
		bodyFn(lines, t);
	}
}

/**
 * Appends the standard "Generated by Jolli Memory" footer. When `summary`
 * carries provider attribution (`llm.source`) it is appended as
 * `· via <provider>`. Clipboard/folder callers pass no `summary`, preserving
 * the original two-segment footer. Exported so the PR builders reuse it.
 */
export function pushFooter(lines: Array<string>, summary?: CommitSummary): void {
	const generatedAt = formatFullDate(new Date().toISOString());
	const provider = summary ? formatProviderLabel(summary) : undefined;
	const tail = provider ? ` · via ${provider}` : "";
	lines.push("", "---", "", `*Generated by Jolli Memory · ${generatedAt}${tail}*`);
}
