/**
 * WikiMarkdownBuilder — pure renderers for the topic-KB wiki layer at
 * `<kbRoot>/_wiki/`. No fs, no LLM, no storage — callers wire to disk.
 *
 * Kept functions (SP3): renderTopicImpl, renderTopicKBIndex, topicPageToCompiledTopic.
 * The legacy MergedKnowledge-based renderTopic/renderIndex were removed in SP5.
 */

import type { CompiledTopic } from "../Types.js";
import type { TopicPage } from "./TopicKBTypes.js";

/**
 * Caller-supplied context: how to render wikilinks pointing OUT of the
 * wiki tree. Source commits live under per-branch folders next to the
 * `_wiki/` directory; the visible markdown filename includes the commit
 * message slug, which only the caller can resolve (it lives in the
 * SummaryIndex). When a commit's visible filename can't be resolved,
 * caller passes `null` and we fall back to a non-link literal.
 */
export interface WikiRenderContext {
	/** Repo display name (e.g. "jolliai"); only used for the index `_index.md` H1. */
	readonly repoName: string;
	/**
	 * Lookup helper from short commit hash (8-char hex prefix) to the
	 * visible-md path **relative to `<kbRoot>/_wiki/`**. Returns null when
	 * no visible summary exists (orphan-only mode / hash unknown).
	 * Expected return shape: `../<branchFolder>/summary--<slug>-<hash8>.md`.
	 */
	readonly resolveCommitVisiblePath: (commitHash8: string) => string | null;
	/**
	 * Lookup helper from branch name to the visible branch folder name
	 * (e.g. `"feature/oauth"` → `"feature-oauth"`). Returns null when
	 * unknown (caller's branches.json miss).
	 */
	readonly resolveBranchFolder: (branch: string) => string | null;
	/** Commit hash 8-char prefix → commit message; used for link display text. */
	readonly resolveCommitMessage: (commitHash8: string) => string | null;
}

const GENERATED_BANNER = "<!-- Generated by Jolli Memory · do not edit — regenerated on every merge -->";

/** Shape-agnostic topic render: takes branches + lastUpdatedAt directly instead
 *  of a MergedKnowledge container, so topic-KB pages can render without one. */
export function renderTopicImpl(
	topic: CompiledTopic,
	branches: ReadonlyArray<string>,
	lastUpdatedAt: string,
	ctx: WikiRenderContext,
): string {
	const lines: string[] = [];
	lines.push(`# ${topic.title}`);
	lines.push("");
	lines.push(GENERATED_BANNER);
	lines.push("");
	lines.push(`> **Source branches:** ${branches.join(", ")}`);
	lines.push(`> **Merged:** ${lastUpdatedAt}`);
	lines.push(`> **Topic slug:** \`${topic.stableSlug}\` (stable across re-merges)`);
	lines.push("");
	lines.push(topic.content.trim());
	lines.push("");

	if (topic.keyDecisions && topic.keyDecisions.length > 0) {
		lines.push("## Key Decisions");
		lines.push("");
		for (const decision of topic.keyDecisions) {
			lines.push(`- ${decision}`);
		}
		lines.push("");
	}

	if (topic.sourceCommits.length > 0) {
		lines.push("## Source Commits");
		lines.push("");
		for (const commitHash of topic.sourceCommits) {
			const hash8 = commitHash.substring(0, 8);
			const path = ctx.resolveCommitVisiblePath(hash8);
			const message = ctx.resolveCommitMessage(hash8);
			// Standard Markdown relative link: clickable in VS Code preview and
			// GitHub, and still resolved by Obsidian. When the visible MD isn't on
			// disk (orphan-only mode / unknown hash), drop the link target and just
			// show the hash + message so the reader still sees a citation.
			if (path && message) {
				lines.push(`- ${mdLink(hash8, stripLeadingDotSlash(path))} — ${message}`);
			} else if (message) {
				lines.push(`- \`${hash8}\` — ${message}`);
			} else {
				lines.push(`- \`${hash8}\``);
			}
		}
		lines.push("");
	}

	if (topic.relatedBranches && topic.relatedBranches.length > 0) {
		lines.push("## Related Branches");
		lines.push("");
		for (const branch of topic.relatedBranches) {
			const folder = ctx.resolveBranchFolder(branch);
			if (folder) {
				lines.push(`- ${mdLink(branch, `../${folder}/`)}`);
			} else {
				lines.push(`- \`${branch}\``);
			}
		}
		lines.push("");
	}

	return lines.join("\n");
}

/** Adapts a topic-KB page to the CompiledTopic shape the renderer expects.
 *  Only summary-type sourceRefs are commit hashes. */
export function topicPageToCompiledTopic(page: TopicPage): CompiledTopic {
	return {
		title: page.title,
		stableSlug: page.stableSlug,
		content: page.content,
		...(page.relatedBranches.length > 0 && { relatedBranches: [...page.relatedBranches] }),
		sourceCommits: page.sourceRefs.filter((r) => r.type === "summary").map((r) => r.id),
	};
}

/**
 * Renders a topic-KB index page from a flat list of compiled topics.
 * Shape-agnostic: takes topics + repoName directly, not a MergedKnowledge.
 * Used by FolderStorage.renderTopicWiki (SP3) where there is no MergedKnowledge.
 */
export function renderTopicKBIndex(topics: ReadonlyArray<CompiledTopic>, ctx: WikiRenderContext): string {
	const lines: string[] = [];
	lines.push(`# ${ctx.repoName} · Knowledge Wiki`);
	lines.push("");
	lines.push(GENERATED_BANNER);
	lines.push("");
	lines.push(`> **${topics.length} topics** in the knowledge base`);
	lines.push("");

	if (topics.length > 0) {
		lines.push("## Topics");
		lines.push("");
		for (const topic of topics) {
			lines.push(`- ${mdLink(topic.title, `topic--${topic.stableSlug}.md`)}`);
		}
		lines.push("");
	}

	return lines.join("\n");
}

function stripLeadingDotSlash(path: string): string {
	return path.startsWith("./") ? path.substring(2) : path;
}

/**
 * Standard Markdown link `[label](target)`. Escapes brackets in the label and
 * percent-encodes the few characters in the target that would otherwise close
 * the `(...)` destination early — so the link stays clickable in VS Code's
 * Markdown preview and GitHub, and is still resolved by Obsidian. We do NOT use
 * Obsidian `[[wikilinks]]` here: those render as plain text everywhere except
 * Obsidian (and Foam-style VS Code extensions).
 */
function mdLink(label: string, target: string): string {
	const safeLabel = label.replace(/[\\[\]]/g, "\\$&");
	const safeTarget = target.replace(/ /g, "%20").replace(/\(/g, "%28").replace(/\)/g, "%29");
	return `[${safeLabel}](${safeTarget})`;
}
