package ai.jolli.jollimemory.toolwindow.views

import ai.jolli.jollimemory.core.CommitSummary
import ai.jolli.jollimemory.core.E2eTestScenario
import ai.jolli.jollimemory.core.SummaryTree
import ai.jolli.jollimemory.toolwindow.views.SummaryUtils.ViewTopicWithDate
import ai.jolli.jollimemory.toolwindow.views.SummaryUtils.collectSortedTopics
import ai.jolli.jollimemory.toolwindow.views.SummaryUtils.formatDate
import ai.jolli.jollimemory.toolwindow.views.SummaryUtils.formatFullDate
import ai.jolli.jollimemory.toolwindow.views.SummaryUtils.groupTopicsByDate
import ai.jolli.jollimemory.toolwindow.views.SummaryUtils.padIndex

/**
 * SummaryMarkdownBuilder
 *
 * Builds a Markdown string from a CommitSummary for clipboard export and
 * Jolli Space publishing. Structure mirrors the webview layout.
 */
object SummaryMarkdownBuilder {

    /**
     * Builds a Markdown string from a CommitSummary for clipboard export.
     *
     * Structure mirrors the webview layout:
     * - H1: commit message
     * - Properties table: Commit, Branch, Author, Date, Changes
     * - Source Commits list (only for squash/multi-record summaries)
     * - Memories: numbered, each field rendered as a blockquote callout
     * - Footer: "Generated by JolliMemory"
     */
    fun buildMarkdown(summary: CommitSummary): String {
        val (allTopics, sourceNodes, showRecordDates) = collectSortedTopics(summary)
        val lines = mutableListOf<String>()

        pushPropertiesSection(lines, summary)
        pushPlansSection(lines, summary, includeEditInfo = true)
        pushE2eTestSection(lines, summary.e2eTestGuide)
        pushSourceCommitsSection(lines, sourceNodes)
        pushTopicsSection(lines, allTopics, showRecordDates, ::pushTopicBody)
        pushFooter(lines)

        return lines.joinToString("\n")
    }

    /**
     * Builds a simplified Markdown string optimized for GitHub PR descriptions.
     *
     * Only includes information not already visible on the PR page:
     * - Jolli Memory URL (if pushed)
     * - Associated Plans with URLs
     * - E2E Test Guide
     * - Summaries: Why (trigger) -> Decisions -> What (response)
     * - Footer
     */
    fun buildPrMarkdown(summary: CommitSummary): String {
        val (allTopics, _, showRecordDates) = collectSortedTopics(summary)
        val lines = mutableListOf<String>()

        // Jolli Memory URL
        val memoryDocUrl = summary.jolliDocUrl
        if (memoryDocUrl != null) {
            lines.addAll(listOf("", "## Jolli Memory", "", memoryDocUrl))
        }

        pushPlansSection(lines, summary, includeEditInfo = false)
        pushE2eTestSection(lines, summary.e2eTestGuide)
        pushPrTopicsSection(lines, allTopics, showRecordDates)
        pushFooter(lines)

        return lines.joinToString("\n")
    }

    // ── Shared section helpers ──────────────────────────────────────────────

    /** Appends the commit properties header (H1, metadata list, separator). */
    private fun pushPropertiesSection(lines: MutableList<String>, summary: CommitSummary) {
        val aggStats = SummaryTree.aggregateStats(summary)
        val totalFiles = aggStats.filesChanged
        val totalTurns = SummaryTree.aggregateTurns(summary)

        val filesLabel = "$totalFiles file${if (totalFiles != 1) "s" else ""} changed, " +
            "+${aggStats.insertions} insertions, \u2212${aggStats.deletions} deletions"
        val dateLabel = formatFullDate(summary.commitDate)

        lines.addAll(
            listOf(
                "# ${summary.commitMessage}",
                "",
                "- **Commit:** `${summary.commitHash}`",
                "- **Branch:** `${summary.branch}`",
                "- **Author:** ${summary.commitAuthor}",
                "- **Date:** $dateLabel",
                "- **Duration:** ${SummaryTree.formatDurationLabel(summary)}",
                "- **Changes:** $filesLabel",
            )
        )

        if (totalTurns > 0) {
            lines.add("- **Conversations:** $totalTurns turn${if (totalTurns != 1) "s" else ""}")
        }

        val memoryDocUrl = summary.jolliDocUrl
        if (memoryDocUrl != null) {
            lines.add("- **Jolli Memory:** [$memoryDocUrl]($memoryDocUrl)")
        }

        lines.addAll(listOf("", "---"))
    }

    /**
     * Appends the plans section. When [includeEditInfo] is true (clipboard export),
     * shows edit count for plans without a Jolli URL.
     */
    private fun pushPlansSection(lines: MutableList<String>, summary: CommitSummary, includeEditInfo: Boolean) {
        val plans = summary.plans
        if (plans.isNullOrEmpty()) return

        val planCount = if (plans.size > 1) " (${plans.size})" else ""
        lines.addAll(listOf("", "## Plans$planCount", ""))

        for (plan in plans) {
            val planUrl = plan.jolliPlanDocUrl
            if (planUrl != null) {
                lines.add("- ${plan.title}")
                lines.add("  $planUrl")
            } else if (includeEditInfo) {
                lines.add("- ${plan.title}")
                lines.add("  _(${plan.slug}.md \u00b7 edited ${plan.editCount} time${if (plan.editCount != 1) "s" else ""})_")
            } else {
                lines.add("- ${plan.title}")
            }
        }

        if (includeEditInfo) {
            lines.addAll(listOf("", "---"))
        }
    }

    /** Appends the E2E test guide section (shared between clipboard and PR markdown). */
    private fun pushE2eTestSection(lines: MutableList<String>, e2eTestGuide: List<E2eTestScenario>?) {
        if (e2eTestGuide.isNullOrEmpty()) return

        lines.addAll(listOf("", "## E2E Test (${e2eTestGuide.size})"))

        for ((i, s) in e2eTestGuide.withIndex()) {
            lines.addAll(listOf("", "### ${i + 1}. ${s.title}"))
            if (s.preconditions != null) {
                lines.addAll(listOf("", "**Preconditions:** ${s.preconditions}"))
            }
            lines.addAll(listOf("", "**Steps:**"))
            for ((j, step) in s.steps.withIndex()) {
                lines.add("${j + 1}. $step")
            }
            lines.addAll(listOf("", "**Expected Results:**"))
            for (r in s.expectedResults) {
                lines.add("- $r")
            }
        }

        lines.addAll(listOf("", "---"))
    }

    /** Appends the source commits section (only for squash/multi-record summaries). */
    private fun pushSourceCommitsSection(lines: MutableList<String>, sourceNodes: List<CommitSummary>) {
        if (sourceNodes.size <= 1) return

        lines.addAll(listOf("", "## Source Commits (${sourceNodes.size})"))

        for (node in sourceNodes) {
            val ins = node.stats?.insertions ?: 0
            val del = node.stats?.deletions ?: 0
            val turnsMd = if (node.conversationTurns != null) " \u00b7 ${node.conversationTurns} turns" else ""
            lines.add(
                "- `${node.commitHash.take(8)}` ${node.commitMessage}  " +
                    "_(+$ins \u2212$del$turnsMd \u00b7 ${formatDate(node.commitDate)})_"
            )
        }

        lines.addAll(listOf("", "---"))
    }

    /** Appends the full topic body fields (trigger, decisions, response, todo, files). */
    private fun pushTopicBody(out: MutableList<String>, t: ViewTopicWithDate) {
        val topic = t.topic.topic
        out.addAll(listOf("", "**\u26A1 Why This Change**", "", topic.trigger))
        out.addAll(listOf("", "**\uD83D\uDCA1 Decisions Behind the Code**", "", topic.decisions))
        out.addAll(listOf("", "**\u2705 What Was Implemented**", "", topic.response))
        if (topic.todo != null) {
            out.addAll(listOf("", "**\uD83D\uDCCB Future Enhancements**", "", topic.todo))
        }
        if (!topic.filesAffected.isNullOrEmpty()) {
            out.addAll(listOf("", "**\uD83D\uDCC1 FILES**"))
            for (f in topic.filesAffected) {
                out.add("- `$f`")
            }
        }
    }

    /** Appends simplified topic body for PR: trigger, decisions, response (no todo/files). */
    private fun pushPrTopicBody(out: MutableList<String>, t: ViewTopicWithDate) {
        val topic = t.topic.topic
        out.addAll(listOf("", "**\u26A1 Why This Change**", "", topic.trigger))
        out.addAll(listOf("", "**\uD83D\uDCA1 Decisions Behind the Code**", "", topic.decisions))
        out.addAll(listOf("", "**\u2705 What Was Implemented**", "", topic.response))
    }

    /** Appends the memories/summaries section for clipboard export. */
    private fun pushTopicsSection(
        lines: MutableList<String>,
        allTopics: List<ViewTopicWithDate>,
        showRecordDates: Boolean,
        bodyFn: (MutableList<String>, ViewTopicWithDate) -> Unit,
    ) {
        if (allTopics.isEmpty()) return

        val heading = if (allTopics.size == 1) "Summary" else "Summaries"
        lines.addAll(listOf("", "## $heading (${allTopics.size})"))

        if (showRecordDates) {
            var globalIdx = 0
            for ((_, groupTopics) in groupTopicsByDate(allTopics)) {
                val groupDate = formatDate(groupTopics[0].recordDate ?: "")
                lines.addAll(listOf("", "### $groupDate"))
                for (t in groupTopics) {
                    val catLabel = if (t.topic.topic.category != null) " `${t.topic.topic.category}`" else ""
                    lines.addAll(listOf("", "#### ${padIndex(globalIdx)} \u00b7 ${t.topic.topic.title}$catLabel"))
                    bodyFn(lines, t)
                    globalIdx++
                }
            }
        } else {
            for ((i, t) in allTopics.withIndex()) {
                val catLabel = if (t.topic.topic.category != null) " `${t.topic.topic.category}`" else ""
                lines.addAll(listOf("", "### ${padIndex(i)} \u00b7 ${t.topic.topic.title}$catLabel"))
                bodyFn(lines, t)
            }
        }
    }

    /**
     * Appends the PR summaries section with GitHub body-size truncation.
     * Uses simplified topic body (no todo/files) and stops adding topics
     * once the PR body would exceed the GitHub character limit.
     */
    private fun pushPrTopicsSection(
        lines: MutableList<String>,
        allTopics: List<ViewTopicWithDate>,
        showRecordDates: Boolean,
    ) {
        if (allTopics.isEmpty()) return

        // GitHub PR body limit is 65536 chars. Reserve space for footer + markers (~200 chars).
        val prBodyLimit = 65_000

        val heading = if (allTopics.size == 1) "Summary" else "Summaries"
        lines.addAll(listOf("", "## $heading (${allTopics.size})"))

        val currentLength = { lines.joinToString("\n").length }
        val includedCount: Int

        if (showRecordDates) {
            includedCount = pushPrTopicsGroupedByDate(lines, allTopics, currentLength, prBodyLimit)
        } else {
            var count = 0
            for ((i, t) in allTopics.withIndex()) {
                val topicLines = mutableListOf<String>()
                topicLines.addAll(listOf("", "### ${padIndex(i)} \u00b7 ${t.topic.topic.title}"))
                pushPrTopicBody(topicLines, t)
                if (currentLength() + topicLines.joinToString("\n").length > prBodyLimit) break
                lines.addAll(topicLines)
                count++
            }
            includedCount = count
        }

        val omitted = allTopics.size - includedCount
        if (omitted > 0) {
            val noun = if (omitted != 1) "ies" else "y"
            lines.addAll(listOf("", "> \u26A0\uFE0F $omitted more summar$noun omitted due to GitHub PR body size limit."))
        }
    }

    /** Appends date-grouped PR topics with truncation. Returns the number of included topics. */
    private fun pushPrTopicsGroupedByDate(
        lines: MutableList<String>,
        allTopics: List<ViewTopicWithDate>,
        currentLength: () -> Int,
        limit: Int,
    ): Int {
        var globalIdx = 0
        var includedCount = 0
        var truncated = false

        for ((_, groupTopics) in groupTopicsByDate(allTopics)) {
            if (truncated) break
            val groupDate = formatDate(groupTopics[0].recordDate ?: "")
            lines.addAll(listOf("", "### $groupDate"))
            for (t in groupTopics) {
                val topicLines = mutableListOf<String>()
                topicLines.addAll(listOf("", "#### ${padIndex(globalIdx)} \u00b7 ${t.topic.topic.title}"))
                pushPrTopicBody(topicLines, t)
                if (currentLength() + topicLines.joinToString("\n").length > limit) {
                    truncated = true
                    break
                }
                lines.addAll(topicLines)
                includedCount++
                globalIdx++
            }
        }
        return includedCount
    }

    /** Appends the standard "Generated by JolliMemory" footer. */
    private fun pushFooter(lines: MutableList<String>) {
        val generatedAt = formatFullDate(java.time.Instant.now().toString())
        lines.addAll(listOf("", "---", "", "*Generated by JolliMemory \u00b7 $generatedAt*"))
    }
}
