/**
 * SummaryMarkdownBuilder
 *
 * Re-exports the markdown builder from the core jollimemory package.
 * The implementation lives in cli/src/core/SummaryMarkdownBuilder.ts.
 */

import {
	aggregateStats,
	aggregateTurns,
	formatDurationLabel,
} from "../../../cli/src/core/SummaryTree.js";
import type { CommitSummary, E2eTestScenario } from "../../../cli/src/Types.js";
import {
	collectSortedTopics,
	escHtml,
	formatDate,
	formatFullDate,
	getDisplayDate,
	groupTopicsByDate,
	padIndex,
	type TopicWithDate,
} from "./SummaryUtils.js";

/**
 * Builds a Markdown string from a CommitSummary for clipboard export.
 *
 * Structure mirrors the webview layout:
 * - H1: commit message
 * - Properties table: Commit, Branch, Author, Date, Changes
 * - Source Commits list (only for squash/multi-record summaries)
 * - Memories: numbered, each field rendered as a blockquote callout
 * - Footer: "Generated by Jolli Memory"
 */
export function buildMarkdown(summary: CommitSummary): string {
	const {
		topics: allTopics,
		sourceNodes,
		showRecordDates,
	} = collectSortedTopics(summary);
	const lines: Array<string> = [];

	pushPropertiesSection(lines, summary);
	pushPlansAndNotesSection(lines, summary);
	pushE2eTestSection(lines, summary.e2eTestGuide);
	pushSourceCommitsSection(lines, sourceNodes);
	pushTopicsSection(lines, allTopics, showRecordDates, pushTopicBody);
	pushFooter(lines);

	return lines.join("\n");
}

/**
 * Builds a simplified Markdown string optimized for GitHub PR descriptions.
 *
 * Only includes information not already visible on the PR page:
 * - Jolli Memory URL (if pushed)
 * - Associated Plans with URLs
 * - E2E Test Guide
 * - Summaries: Why (trigger) -> Decisions -> What (response)
 * - Footer
 */
export function buildPrMarkdown(summary: CommitSummary): string {
	const { topics: allTopics, showRecordDates } = collectSortedTopics(summary);
	const lines: Array<string> = [];

	// Jolli Memory URL
	const memoryDocUrl = summary.jolliDocUrl;
	if (memoryDocUrl) {
		lines.push("", `## Jolli Memory`, "", `${memoryDocUrl}`);
	}

	pushPlansAndNotesSection(lines, summary);
	pushE2eTestSection(lines, summary.e2eTestGuide, true);
	pushPrTopicsSection(lines, allTopics, showRecordDates);
	pushFooter(lines);

	return lines.join("\n");
}

// ── Shared section helpers ──────────────────────────────────────────────────

/** Appends the commit properties header (H1, metadata list, separator). */
function pushPropertiesSection(
	lines: Array<string>,
	summary: CommitSummary,
): void {
	const aggStats = aggregateStats(summary);
	const totalFiles = aggStats.filesChanged;
	const totalTurns = aggregateTurns(summary);

	const filesLabel = `${totalFiles} file${totalFiles !== 1 ? "s" : ""} changed, +${aggStats.insertions} insertions, \u2212${aggStats.deletions} deletions`;
	const dateLabel = formatFullDate(getDisplayDate(summary));

	lines.push(
		`# ${summary.commitMessage}`,
		"",
		`- **Commit:** \`${summary.commitHash}\``,
		`- **Branch:** \`${summary.branch}\``,
		`- **Author:** ${summary.commitAuthor}`,
		`- **Date:** ${dateLabel}`,
		`- **Duration:** ${formatDurationLabel(summary)}`,
		`- **Changes:** ${filesLabel}`,
	);

	if (totalTurns > 0) {
		lines.push(
			`- **Conversations:** ${totalTurns} turn${totalTurns !== 1 ? "s" : ""}`,
		);
	}

	const memoryDocUrl = summary.jolliDocUrl;
	if (memoryDocUrl) {
		lines.push(`- **Jolli Memory:** [${memoryDocUrl}](${memoryDocUrl})`);
	}

	lines.push("", "---");
}

/** Appends a combined Plans & Notes section — title + URL for each item. */
function pushPlansAndNotesSection(
	lines: Array<string>,
	summary: CommitSummary,
): void {
	const plans = summary.plans ?? [];
	const notes = summary.notes ?? [];
	const totalCount = plans.length + notes.length;
	if (totalCount === 0) {
		return;
	}
	const countLabel = totalCount > 1 ? ` (${totalCount})` : "";
	lines.push("", `## Plans & Notes${countLabel}`, "");

	for (const plan of plans) {
		const planUrl = plan.jolliPlanDocUrl;
		lines.push(planUrl ? `- [${plan.title}](${planUrl})` : `- ${plan.title}`);
	}

	for (const note of notes) {
		const noteUrl = note.jolliNoteDocUrl;
		lines.push(noteUrl ? `- [${note.title}](${noteUrl})` : `- ${note.title}`);
	}
}

/**
 * Appends the E2E test guide section.
 *
 * Shared between clipboard and PR markdown. When `foldScenarios` is true
 * (PR path), each scenario is wrapped in a GitHub <details>/<summary> block
 * and user-provided fields are sanitized against <details>/<summary> tag
 * injection. Default behavior (foldScenarios=false) emits plain markdown
 * headings unchanged for clipboard export.
 */
function pushE2eTestSection(
	lines: Array<string>,
	e2eTestGuide: ReadonlyArray<E2eTestScenario> | undefined,
	foldScenarios = false,
): void {
	if (!e2eTestGuide || e2eTestGuide.length === 0) {
		return;
	}
	lines.push("", `## E2E Test (${e2eTestGuide.length})`);
	for (let i = 0; i < e2eTestGuide.length; i++) {
		const s = e2eTestGuide[i];
		if (foldScenarios) {
			const summaryContent = `<strong>${i + 1}. ${escHtml(s.title)}</strong>`;
			const bodyOnly: Array<string> = [];
			if (s.preconditions) {
				bodyOnly.push(
					"",
					`**Preconditions:** ${escapeGithubWrapperTags(s.preconditions)}`,
				);
			}
			bodyOnly.push("", "**Steps:**");
			for (let j = 0; j < s.steps.length; j++) {
				bodyOnly.push(`${j + 1}. ${escapeGithubWrapperTags(s.steps[j])}`);
			}
			bodyOnly.push("", "**Expected Results:**");
			for (const r of s.expectedResults) {
				bodyOnly.push(`- ${escapeGithubWrapperTags(r)}`);
			}
			lines.push(...wrapInGithubDetails(summaryContent, bodyOnly));
		} else {
			lines.push("", `### ${i + 1}. ${s.title}`);
			if (s.preconditions) {
				lines.push("", `**Preconditions:** ${s.preconditions}`);
			}
			lines.push("", "**Steps:**");
			for (let j = 0; j < s.steps.length; j++) {
				lines.push(`${j + 1}. ${s.steps[j]}`);
			}
			lines.push("", "**Expected Results:**");
			for (const r of s.expectedResults) {
				lines.push(`- ${r}`);
			}
		}
	}
	lines.push("", "---");
}

/** Appends the source commits section (only for squash/multi-record summaries). */
function pushSourceCommitsSection(
	lines: Array<string>,
	sourceNodes: ReadonlyArray<CommitSummary>,
): void {
	if (sourceNodes.length <= 1) {
		return;
	}
	lines.push("", `## Source Commits (${sourceNodes.length})`);
	for (const node of sourceNodes) {
		const ins = node.stats?.insertions ?? 0;
		const del = node.stats?.deletions ?? 0;
		const turnsMd = node.conversationTurns
			? ` · ${node.conversationTurns} turns`
			: "";
		lines.push(
			`- \`${node.commitHash.substring(0, 8)}\` ${node.commitMessage}  _(+${ins} \u2212${del}${turnsMd} · ${formatDate(getDisplayDate(node))})_`,
		);
	}
	lines.push("", "---");
}

/** Appends the full topic body fields (trigger, decisions, response, todo, files). */
function pushTopicBody(out: Array<string>, t: TopicWithDate): void {
	out.push("", `**⚡ Why This Change**`, "", t.trigger);
	out.push("", `**💡 Decisions Behind the Code**`, "", t.decisions);
	out.push("", `**✅ What Was Implemented**`, "", t.response);
	if (t.todo) {
		out.push("", `**📋 Future Enhancements**`, "", t.todo);
	}
	if (t.filesAffected && t.filesAffected.length > 0) {
		out.push("", `**📁 FILES**`);
		for (const f of t.filesAffected) {
			out.push(`- \`${f}\``);
		}
	}
}

/** Appends the memories/summaries section for clipboard export. */
function pushTopicsSection(
	lines: Array<string>,
	allTopics: Array<TopicWithDate>,
	showRecordDates: boolean,
	bodyFn: (out: Array<string>, t: TopicWithDate) => void,
): void {
	if (allTopics.length === 0) {
		return;
	}
	lines.push(
		"",
		`## ${allTopics.length === 1 ? "Summary" : "Summaries"} (${allTopics.length})`,
	);
	if (showRecordDates) {
		let globalIdx = 0;
		for (const [, groupTopics] of groupTopicsByDate(allTopics)) {
			const groupDate = formatDate(groupTopics[0].recordDate ?? "");
			lines.push("", `### ${groupDate}`);
			for (const t of groupTopics) {
				const catLabel = t.category ? ` \`${t.category}\`` : "";
				lines.push("", `#### ${padIndex(globalIdx)} · ${t.title}${catLabel}`);
				bodyFn(lines, t);
				globalIdx++;
			}
		}
	} else {
		for (let i = 0; i < allTopics.length; i++) {
			const t = allTopics[i];
			const catLabel = t.category ? ` \`${t.category}\`` : "";
			lines.push("", `### ${padIndex(i)} · ${t.title}${catLabel}`);
			bodyFn(lines, t);
		}
	}
}

// ── GitHub PR path (uses GitHub-flavored HTML, not portable) ─────────────
// Helpers below emit <details>/<summary> HTML that only GitHub renders.
// Do NOT reuse from clipboard export (buildMarkdown) or Jolli doc paths —
// other markdown renderers will show raw tags or break rendering.

/**
 * Wraps a block of lines with <details>/<summary> for GitHub PR folding.
 *
 * `summaryContent` is emitted inline inside `<summary>...</summary>` (no
 * blank lines around it) — markdown headings inside summary are avoided to
 * prevent GitHub's heading CSS (24px top + 16px bottom margin) from bloating
 * every collapsed row. Callers typically pass `<strong>NN · Title</strong>`
 * for a tight bold label.
 *
 * A `<br>` is inserted after `</summary>` so that when the block is expanded,
 * the inline summary label and the first body paragraph don't collide
 * visually — `<p>` has `margin-top: 0` under GitHub's CSS, which otherwise
 * makes the expanded content feel glued to the label.
 *
 * Body is wrapped in `<blockquote>...</blockquote>` so the expanded content
 * gets GitHub's blockquote styling (left border + indent + slightly dimmed
 * text). This gives each expanded topic a clear visual container that
 * distinguishes it from the summary label. GFM parses markdown inside the
 * blockquote when blank lines flank the HTML tags (type-6 HTML block rule).
 *
 * `bodyLines` is expected to begin with "" so that the blank line between
 * `<blockquote>` and the first body block is preserved (needed by GFM to
 * switch from HTML mode to markdown parsing inside the blockquote).
 */
function wrapInGithubDetails(
	summaryContent: string,
	bodyLines: Array<string>,
): Array<string> {
	return [
		"<details>",
		`<summary>${summaryContent}</summary>`,
		"<br>",
		"<blockquote>",
		...bodyLines,
		"",
		"</blockquote>",
		"</details>",
	];
}

/**
 * Escapes the block-level HTML tags used by `wrapInGithubDetails` so that
 * Claude-generated body content cannot prematurely close our outer wrappers.
 *
 * Two wrapper boundaries need protection:
 * - `<details>` / `</details>` — the outer collapsible block
 * - `<blockquote>` / `</blockquote>` — the inner visual container for body
 *
 * Both opening (including attribute variants like `<details open>`) and
 * closing tags are escaped to `&lt;...&gt;`. Other HTML tags (`<summary>`,
 * `<code>`, `<br>`, `<img>`, etc.) and markdown formatting are preserved.
 *
 * NOTE: Only applied to generated content inside buildPrMarkdown. User-edited
 * textarea content is NOT re-sanitized on submit (by design).
 */
function escapeGithubWrapperTags(text: string): string {
	return text
		.replace(/<details\b[^>]*>/gi, (m) => `&lt;${m.slice(1, -1)}&gt;`)
		.replace(/<\/details\s*>/gi, "&lt;/details&gt;")
		.replace(/<blockquote\b[^>]*>/gi, (m) => `&lt;${m.slice(1, -1)}&gt;`)
		.replace(/<\/blockquote\s*>/gi, "&lt;/blockquote&gt;");
}

/** Appends simplified topic body for PR: trigger, decisions, response (no todo/files). */
function pushPrTopicBody(out: Array<string>, t: TopicWithDate): void {
	out.push(
		"",
		`**⚡ Why This Change**`,
		"",
		escapeGithubWrapperTags(t.trigger),
	);
	out.push(
		"",
		`**💡 Decisions Behind the Code**`,
		"",
		escapeGithubWrapperTags(t.decisions),
	);
	out.push(
		"",
		`**✅ What Was Implemented**`,
		"",
		escapeGithubWrapperTags(t.response),
	);
}

/**
 * Appends the PR summaries section with GitHub body-size truncation.
 * Uses simplified topic body (no todo/files) and stops adding topics
 * once the PR body would exceed the GitHub character limit.
 */
function pushPrTopicsSection(
	lines: Array<string>,
	allTopics: Array<TopicWithDate>,
	showRecordDates: boolean,
): void {
	if (allTopics.length === 0) {
		return;
	}

	// GitHub PR body limit is 65536 chars. Reserve space for footer + markers (~200 chars).
	const PR_BODY_LIMIT = 65000;

	lines.push(
		"",
		`## ${allTopics.length === 1 ? "Summary" : "Summaries"} (${allTopics.length})`,
	);
	let includedCount = 0;
	const currentLength = () => lines.join("\n").length;

	if (showRecordDates) {
		includedCount = pushPrTopicsGroupedByDate(
			lines,
			allTopics,
			currentLength,
			PR_BODY_LIMIT,
		);
	} else {
		for (let i = 0; i < allTopics.length; i++) {
			const summaryContent = `<strong>${padIndex(i)} · ${escHtml(allTopics[i].title)}</strong>`;
			const bodyOnly: Array<string> = [];
			pushPrTopicBody(bodyOnly, allTopics[i]);
			const topicLines = wrapInGithubDetails(summaryContent, bodyOnly);
			if (currentLength() + topicLines.join("\n").length > PR_BODY_LIMIT) {
				break;
			}
			lines.push(...topicLines);
			includedCount++;
		}
	}

	const omitted = allTopics.length - includedCount;
	if (omitted > 0) {
		lines.push(
			"",
			`> ⚠️ ${omitted} more summar${omitted !== 1 ? "ies" : "y"} omitted due to GitHub PR body size limit.`,
		);
	}
}

/**
 * Appends date-grouped PR topics with truncation. Returns the number of
 * included topics.
 *
 * Group header `### <date>` is written **atomically** with the first topic
 * of its group — if the first topic doesn't fit, the group header is also
 * skipped, avoiding an orphan date header with no content.
 */
function pushPrTopicsGroupedByDate(
	lines: Array<string>,
	allTopics: Array<TopicWithDate>,
	currentLength: () => number,
	limit: number,
): number {
	let globalIdx = 0;
	let includedCount = 0;
	let truncated = false;

	for (const [, groupTopics] of groupTopicsByDate(allTopics)) {
		if (truncated) {
			break;
		}
		const groupDate = formatDate(groupTopics[0].recordDate ?? "");
		let groupHeaderPushed = false;
		for (const t of groupTopics) {
			const summaryContent = `<strong>${padIndex(globalIdx)} · ${escHtml(t.title)}</strong>`;
			const bodyOnly: Array<string> = [];
			pushPrTopicBody(bodyOnly, t);
			const topicLines = wrapInGithubDetails(summaryContent, bodyOnly);
			const pending = groupHeaderPushed
				? topicLines
				: ["", `### ${groupDate}`, ...topicLines];
			if (currentLength() + pending.join("\n").length > limit) {
				truncated = true;
				break;
			}
			lines.push(...pending);
			groupHeaderPushed = true;
			includedCount++;
			globalIdx++;
		}
	}
	return includedCount;
}

// ── end GitHub PR path ───────────────────────────────────────────────────

/** Appends the standard "Generated by Jolli Memory" footer. */
function pushFooter(lines: Array<string>): void {
	const generatedAt = formatFullDate(new Date().toISOString());
	lines.push("", "---", "", `*Generated by Jolli Memory · ${generatedAt}*`);
}

/**
 * Builds a recall prompt for pasting into Claude Code.
 * Uses the branch name as the recall argument — the CLI does exact branch
 * matching which is more reliable than keyword search by ticket ID.
 */
export function buildClaudeCodeContext(summary: CommitSummary): string {
	return `Invoke the "jolli-recall" skill with args "${summary.branch}".`;
}
