/**
 * SummaryMarkdownBuilder
 *
 * Builds the full clipboard-export Markdown from a `CommitSummary`. Output
 * is portable markdown (no GitHub-flavored HTML) so it renders correctly
 * in the clipboard, Jolli doc pages, and any CommonMark renderer.
 *
 * GitHub PR description output (with <details>/<summary>/<blockquote>
 * folding) lives in `../../../cli/src/core/SummaryPrMarkdownBuilder.ts` via
 * `buildPrMarkdown`. The shared `pushPlansAndNotesSection`, `pushRecapSection`,
 * and `pushFooter` helpers now live in the CLI core too (imported above), not
 * defined here.
 */

import {
	aggregateConversationTokenBreakdown,
	aggregateConversationTokens,
	aggregateTurns,
	formatDurationLabel,
	resolveDiffStats,
} from "../../../cli/src/core/SummaryTree.js";
import type {
	CommitSummary,
	E2eTestScenario,
} from "../../../cli/src/Types.js";
import { pushFooter, pushPlansAndNotesSection, pushRecapSection } from "../../../cli/src/core/SummaryMarkdownBuilder.js";
import {
	collectSortedTopics,
	estimateConversationCostUsd,
	formatDate,
	formatExactCostUsd,
	formatFullDate,
	formatTokensExact,
	getDisplayDate,
	padIndex,
	type TopicWithDate,
} from "./SummaryUtils.js";

/**
 * Builds a Markdown string from a CommitSummary for clipboard export.
 *
 * Structure mirrors the webview layout:
 * - H1: commit message
 * - Properties table: Commit, Branch, Author, Date, Changes
 * - Source Commits list (only for squash/multi-record summaries)
 * - Memories: numbered, each field rendered as a blockquote callout
 * - Footer: "Generated by Jolli Memory"
 */
export function buildMarkdown(summary: CommitSummary): string {
	const { topics: allTopics, sourceNodes } = collectSortedTopics(summary);
	const lines: Array<string> = [];

	pushPropertiesSection(lines, summary);
	pushPlansAndNotesSection(lines, summary, { includeReferences: true });
	pushRecapSection(lines, summary);
	pushE2eTestSection(lines, summary.e2eTestGuide);
	pushSourceCommitsSection(lines, sourceNodes);
	pushTopicsSection(lines, allTopics, pushTopicBody);
	pushFooter(lines, summary);

	return lines.join("\n");
}

// ── Shared section helpers ──────────────────────────────────────────────────

/** Appends the commit properties header (H1, metadata list, separator). */
function pushPropertiesSection(
	lines: Array<string>,
	summary: CommitSummary,
): void {
	const displayStats = resolveDiffStats(summary);
	const totalFiles = displayStats.filesChanged;
	const totalTurns = aggregateTurns(summary);

	const filesLabel = `${totalFiles} file${totalFiles !== 1 ? "s" : ""} changed, +${displayStats.insertions} insertions, −${displayStats.deletions} deletions`;
	const dateLabel = formatFullDate(getDisplayDate(summary));

	lines.push(
		`# ${summary.commitMessage}`,
		"",
		`- **Commit:** \`${summary.commitHash}\``,
		`- **Branch:** \`${summary.branch}\``,
		`- **Author:** ${summary.commitAuthor}`,
		`- **Date:** ${dateLabel}`,
		`- **Duration:** ${formatDurationLabel(summary)}`,
		`- **Changes:** ${filesLabel}`,
	);

	if (totalTurns > 0) {
		lines.push(
			`- **Conversations:** ${totalTurns} turn${totalTurns !== 1 ? "s" : ""}`,
		);
	}

	// Task usage: token total + cache-aware cost estimate, aggregated across the
	// whole consolidation tree (a squash/amend memory carries its tokens on folded
	// children). Three states mirror the VS Code token meter; omit-when-zero matches
	// the Conversations line above. The article shows EXACT figures (thousands-
	// separated counts, precise $) rather than the compact form the UI token bar uses.
	const totalTokens = aggregateConversationTokens(summary);
	if (totalTokens > 0) {
		const agg = aggregateConversationTokenBreakdown(summary);
		const b = agg.input > 0 || agg.output > 0 || agg.cached > 0 ? agg : undefined;
		const cost = formatExactCostUsd(estimateConversationCostUsd(b, totalTokens));
		const split = b
			? ` (${formatTokensExact(b.input)} input, ${formatTokensExact(b.output)} output, ${formatTokensExact(b.cached)} cached)`
			: "";
		lines.push(`- **Task usage:** ${formatTokensExact(totalTokens)} tokens · ${cost}${split}`);
	}

	const memoryDocUrl = summary.jolliDocUrl;
	if (memoryDocUrl) {
		lines.push(`- **Jolli Memory:** [${memoryDocUrl}](${memoryDocUrl})`);
	}

	lines.push("", "---");
}

/**
 * Appends the E2E test guide section for clipboard export. Emits plain
 * markdown H3 headings per scenario.
 *
 * The PR variant lives in `../../../cli/src/core/SummaryPrMarkdownBuilder.ts`
 * (`pushPrE2eTestSection`) and wraps each scenario in a `<details>` block with
 * sanitization.
 */
function pushE2eTestSection(
	lines: Array<string>,
	e2eTestGuide: ReadonlyArray<E2eTestScenario> | undefined,
): void {
	if (!e2eTestGuide || e2eTestGuide.length === 0) {
		return;
	}
	lines.push("", `## E2E Test (${e2eTestGuide.length})`);
	for (let i = 0; i < e2eTestGuide.length; i++) {
		const s = e2eTestGuide[i];
		lines.push("", `### ${i + 1}. ${s.title}`);
		if (s.preconditions) {
			lines.push("", `**Preconditions:** ${s.preconditions}`);
		}
		lines.push("", "**Steps:**");
		for (let j = 0; j < s.steps.length; j++) {
			lines.push(`${j + 1}. ${s.steps[j]}`);
		}
		lines.push("", "**Expected Results:**");
		for (const r of s.expectedResults) {
			lines.push(`- ${r}`);
		}
	}
	lines.push("", "---");
}

/** Appends the source commits section (only for squash/multi-record summaries). */
function pushSourceCommitsSection(
	lines: Array<string>,
	sourceNodes: ReadonlyArray<CommitSummary>,
): void {
	if (sourceNodes.length <= 1) {
		return;
	}
	lines.push("", `## Source Commits (${sourceNodes.length})`);
	for (const node of sourceNodes) {
		const nodeStats = resolveDiffStats(node);
		const turnsMd = node.conversationTurns
			? ` · ${node.conversationTurns} turns`
			: "";
		lines.push(
			`- \`${node.commitHash.substring(0, 8)}\` ${node.commitMessage}  _(+${nodeStats.insertions} −${nodeStats.deletions}${turnsMd} · ${formatDate(getDisplayDate(node))})_`,
		);
	}
	lines.push("", "---");
}

/** Appends the full topic body fields (trigger, decisions, response, todo, files). */
function pushTopicBody(out: Array<string>, t: TopicWithDate): void {
	out.push("", `**⚡ Why This Change**`, "", t.trigger);
	out.push("", `**💡 Decisions Behind the Code**`, "", t.decisions);
	out.push("", `**✅ What Was Implemented**`, "", t.response);
	if (t.todo) {
		out.push("", `**📋 Future Enhancements**`, "", t.todo);
	}
	if (t.filesAffected && t.filesAffected.length > 0) {
		out.push("", `**📁 FILES**`);
		for (const f of t.filesAffected) {
			out.push(`- \`${f}\``);
		}
	}
}

/** Appends the memories/summaries section for clipboard export. Flat list. */
function pushTopicsSection(
	lines: Array<string>,
	allTopics: Array<TopicWithDate>,
	bodyFn: (out: Array<string>, t: TopicWithDate) => void,
): void {
	if (allTopics.length === 0) {
		return;
	}
	lines.push(
		"",
		`## ${allTopics.length === 1 ? "Topic" : "Topics"} (${allTopics.length})`,
	);
	for (let i = 0; i < allTopics.length; i++) {
		const t = allTopics[i];
		const catLabel = t.category ? ` \`${t.category}\`` : "";
		lines.push("", `### ${padIndex(i)} · ${t.title}${catLabel}`);
		bodyFn(lines, t);
	}
}

/**
 * Builds a recall prompt for pasting into Claude Code.
 * Uses the branch name as the recall argument — the CLI does exact branch
 * matching which is more reliable than keyword search by ticket ID.
 */
export function buildClaudeCodeContext(summary: CommitSummary): string {
	return `Invoke the "jolli-recall" skill with args "${summary.branch}".`;
}
