/**
 * SummaryMarkdownBuilder
 *
 * Builds the full clipboard-export Markdown from a `CommitSummary`. Output
 * is portable markdown (no GitHub-flavored HTML) so it renders correctly
 * in the clipboard, Jolli doc pages, and any CommonMark renderer.
 *
 * GitHub PR description output (with <details>/<summary>/<blockquote>
 * folding) lives in `SummaryPrMarkdownBuilder.ts` via `buildPrMarkdown`.
 * That file imports `pushPlansAndNotesSection` and `pushFooter` from here,
 * which is why those helpers are exported.
 */

import {
	aggregateStats,
	aggregateTurns,
	formatDurationLabel,
} from "../../../cli/src/core/SummaryTree.js";
import type { CommitSummary, E2eTestScenario } from "../../../cli/src/Types.js";
import {
	collectSortedTopics,
	formatDate,
	formatFullDate,
	getDisplayDate,
	groupTopicsByDate,
	padIndex,
	type TopicWithDate,
} from "./SummaryUtils.js";

/**
 * Builds a Markdown string from a CommitSummary for clipboard export.
 *
 * Structure mirrors the webview layout:
 * - H1: commit message
 * - Properties table: Commit, Branch, Author, Date, Changes
 * - Source Commits list (only for squash/multi-record summaries)
 * - Memories: numbered, each field rendered as a blockquote callout
 * - Footer: "Generated by Jolli Memory"
 */
export function buildMarkdown(summary: CommitSummary): string {
	const {
		topics: allTopics,
		sourceNodes,
		showRecordDates,
	} = collectSortedTopics(summary);
	const lines: Array<string> = [];

	pushPropertiesSection(lines, summary);
	pushPlansAndNotesSection(lines, summary);
	pushE2eTestSection(lines, summary.e2eTestGuide);
	pushSourceCommitsSection(lines, sourceNodes);
	pushTopicsSection(lines, allTopics, showRecordDates, pushTopicBody);
	pushFooter(lines);

	return lines.join("\n");
}

// ── Shared section helpers ──────────────────────────────────────────────────

/** Appends the commit properties header (H1, metadata list, separator). */
function pushPropertiesSection(
	lines: Array<string>,
	summary: CommitSummary,
): void {
	const aggStats = aggregateStats(summary);
	const totalFiles = aggStats.filesChanged;
	const totalTurns = aggregateTurns(summary);

	const filesLabel = `${totalFiles} file${totalFiles !== 1 ? "s" : ""} changed, +${aggStats.insertions} insertions, −${aggStats.deletions} deletions`;
	const dateLabel = formatFullDate(getDisplayDate(summary));

	lines.push(
		`# ${summary.commitMessage}`,
		"",
		`- **Commit:** \`${summary.commitHash}\``,
		`- **Branch:** \`${summary.branch}\``,
		`- **Author:** ${summary.commitAuthor}`,
		`- **Date:** ${dateLabel}`,
		`- **Duration:** ${formatDurationLabel(summary)}`,
		`- **Changes:** ${filesLabel}`,
	);

	if (totalTurns > 0) {
		lines.push(
			`- **Conversations:** ${totalTurns} turn${totalTurns !== 1 ? "s" : ""}`,
		);
	}

	const memoryDocUrl = summary.jolliDocUrl;
	if (memoryDocUrl) {
		lines.push(`- **Jolli Memory:** [${memoryDocUrl}](${memoryDocUrl})`);
	}

	lines.push("", "---");
}

/**
 * Appends a combined Plans & Notes section — title + URL for each item.
 *
 * Exported because `SummaryPrMarkdownBuilder.buildPrMarkdown` also calls it —
 * plans/notes rendering is identical between clipboard and PR output.
 */
export function pushPlansAndNotesSection(
	lines: Array<string>,
	summary: CommitSummary,
): void {
	const plans = summary.plans ?? [];
	const notes = summary.notes ?? [];
	const totalCount = plans.length + notes.length;
	if (totalCount === 0) {
		return;
	}
	const countLabel = totalCount > 1 ? ` (${totalCount})` : "";
	lines.push("", `## Plans & Notes${countLabel}`, "");

	for (const plan of plans) {
		const planUrl = plan.jolliPlanDocUrl;
		lines.push(planUrl ? `- [${plan.title}](${planUrl})` : `- ${plan.title}`);
	}

	for (const note of notes) {
		const noteUrl = note.jolliNoteDocUrl;
		lines.push(noteUrl ? `- [${note.title}](${noteUrl})` : `- ${note.title}`);
	}
}

/**
 * Appends the E2E test guide section for clipboard export. Emits plain
 * markdown H3 headings per scenario.
 *
 * The PR variant lives in `SummaryPrMarkdownBuilder.pushPrE2eTestSection`
 * and wraps each scenario in a `<details>` block with sanitization.
 */
function pushE2eTestSection(
	lines: Array<string>,
	e2eTestGuide: ReadonlyArray<E2eTestScenario> | undefined,
): void {
	if (!e2eTestGuide || e2eTestGuide.length === 0) {
		return;
	}
	lines.push("", `## E2E Test (${e2eTestGuide.length})`);
	for (let i = 0; i < e2eTestGuide.length; i++) {
		const s = e2eTestGuide[i];
		lines.push("", `### ${i + 1}. ${s.title}`);
		if (s.preconditions) {
			lines.push("", `**Preconditions:** ${s.preconditions}`);
		}
		lines.push("", "**Steps:**");
		for (let j = 0; j < s.steps.length; j++) {
			lines.push(`${j + 1}. ${s.steps[j]}`);
		}
		lines.push("", "**Expected Results:**");
		for (const r of s.expectedResults) {
			lines.push(`- ${r}`);
		}
	}
	lines.push("", "---");
}

/** Appends the source commits section (only for squash/multi-record summaries). */
function pushSourceCommitsSection(
	lines: Array<string>,
	sourceNodes: ReadonlyArray<CommitSummary>,
): void {
	if (sourceNodes.length <= 1) {
		return;
	}
	lines.push("", `## Source Commits (${sourceNodes.length})`);
	for (const node of sourceNodes) {
		const ins = node.stats?.insertions ?? 0;
		const del = node.stats?.deletions ?? 0;
		const turnsMd = node.conversationTurns
			? ` · ${node.conversationTurns} turns`
			: "";
		lines.push(
			`- \`${node.commitHash.substring(0, 8)}\` ${node.commitMessage}  _(+${ins} −${del}${turnsMd} · ${formatDate(getDisplayDate(node))})_`,
		);
	}
	lines.push("", "---");
}

/** Appends the full topic body fields (trigger, decisions, response, todo, files). */
function pushTopicBody(out: Array<string>, t: TopicWithDate): void {
	out.push("", `**⚡ Why This Change**`, "", t.trigger);
	out.push("", `**💡 Decisions Behind the Code**`, "", t.decisions);
	out.push("", `**✅ What Was Implemented**`, "", t.response);
	if (t.todo) {
		out.push("", `**📋 Future Enhancements**`, "", t.todo);
	}
	if (t.filesAffected && t.filesAffected.length > 0) {
		out.push("", `**📁 FILES**`);
		for (const f of t.filesAffected) {
			out.push(`- \`${f}\``);
		}
	}
}

/** Appends the memories/summaries section for clipboard export. */
function pushTopicsSection(
	lines: Array<string>,
	allTopics: Array<TopicWithDate>,
	showRecordDates: boolean,
	bodyFn: (out: Array<string>, t: TopicWithDate) => void,
): void {
	if (allTopics.length === 0) {
		return;
	}
	lines.push(
		"",
		`## ${allTopics.length === 1 ? "Topic" : "Topics"} (${allTopics.length})`,
	);
	if (showRecordDates) {
		let globalIdx = 0;
		for (const [, groupTopics] of groupTopicsByDate(allTopics)) {
			const groupDate = formatDate(groupTopics[0].recordDate ?? "");
			lines.push("", `### ${groupDate}`);
			for (const t of groupTopics) {
				const catLabel = t.category ? ` \`${t.category}\`` : "";
				lines.push("", `#### ${padIndex(globalIdx)} · ${t.title}${catLabel}`);
				bodyFn(lines, t);
				globalIdx++;
			}
		}
	} else {
		for (let i = 0; i < allTopics.length; i++) {
			const t = allTopics[i];
			const catLabel = t.category ? ` \`${t.category}\`` : "";
			lines.push("", `### ${padIndex(i)} · ${t.title}${catLabel}`);
			bodyFn(lines, t);
		}
	}
}

/**
 * Appends the standard "Generated by Jolli Memory" footer.
 *
 * Exported because `SummaryPrMarkdownBuilder.buildPrMarkdown` also calls it —
 * footer content is identical between clipboard and PR output.
 */
export function pushFooter(lines: Array<string>): void {
	const generatedAt = formatFullDate(new Date().toISOString());
	lines.push("", "---", "", `*Generated by Jolli Memory · ${generatedAt}*`);
}

/**
 * Builds a recall prompt for pasting into Claude Code.
 * Uses the branch name as the recall argument — the CLI does exact branch
 * matching which is more reliable than keyword search by ticket ID.
 */
export function buildClaudeCodeContext(summary: CommitSummary): string {
	return `Invoke the "jolli-recall" skill with args "${summary.branch}".`;
}
