/**
 * Remediation copy for a capture that its own sandbox has already doomed.
 *
 * When a coding agent runs `git commit` inside a network-denied sandbox — Codex's
 * default `workspace-write` profile is one — the whole pipeline is trapped with it:
 * the post-commit hook, the detached QueueWorker it spawns, and the local-agent
 * subprocess the worker spawns in turn all inherit the sandbox, so the LLM call can
 * never reach the network. Measured on codex-cli 0.146.0: an inline request resolves
 * to HTTP 000 and a *detached* Node child still gets `ENOTFOUND`, i.e. detaching does
 * not escape it. (Codex's own lifecycle hooks DO run outside the sandbox — that is a
 * separate execution path, not a way out of this one.)
 *
 * That makes both generic closing lines actively wrong. `⚠ … capture did not
 * complete` reads as a transient error worth re-trying, and "analysis continues in
 * the background…" promises work that provably cannot finish. Worse, the queue entry
 * is deleted regardless of outcome (fire-and-forget — see the drain loop in
 * QueueWorker), so nothing picks this commit up later either.
 *
 * So when the environment names the sandbox as the cause, say exactly that, say the
 * memory is gone rather than pending, and point at the one setting that fixes it.
 */

/** Sandboxes we can positively identify as network-denied from the environment. */
export type BlockedSandboxId = "codex";

const SANDBOX_LABEL: Record<BlockedSandboxId, string> = {
	codex: "Codex sandbox",
};

/**
 * The fix, per sandbox. Two options on purpose: the config change is the durable
 * one, committing outside the agent is the escape hatch that needs no config edit.
 */
function fixLines(sandbox: BlockedSandboxId): string[] {
	switch (sandbox) {
		case "codex":
			return [
				"→ Allow network access in ~/.codex/config.toml:",
				"      [sandbox_workspace_write]",
				"      network_access = true",
				"  Or run the commit from a terminal outside Codex.",
			];
	}
}

/**
 * The closing notice for a capture that produced no memory while a network-denied
 * sandbox was in effect.
 *
 * Hedged on purpose. The caller substitutes this for the generic `failed` line
 * whenever the sandbox env marker is present, but presence of the marker is not
 * proof of causation: a failure before the LLM call is ever attempted — a git
 * error, an unwritable state directory — lands here too and has nothing to do with
 * the network. Under this sandbox the LLM call genuinely cannot succeed, so the
 * sandbox is the overwhelmingly likely cause and leads; the hedge plus the
 * `debug.log` pointer is what keeps the rarer case diagnosable.
 *
 * Carrying that pointer is the whole reason this line is written out rather than
 * just borrowing the generic text: the line being replaced
 * (`⚠ … capture did not complete (see .jolli/jollimemory/debug.log)`) was the only
 * one that told the user where the real error is, so dropping it left them with a
 * confident diagnosis and no way to check it.
 *
 * Deliberately promises NO recovery path, because none exists. A sandbox failure
 * that classifies as `local-agent-auth` still stores a placeholder summary, and
 * `jolli backfill` skips every commit that already has one — so this commit cannot
 * be regenerated by any shipped command. Do not add a "run X later" line here
 * without first making that path real.
 */
export function buildSandboxFailureCaptureText(sandbox: BlockedSandboxId): string {
	return [
		`⚠ Jolli Memory: no memory for this commit — most likely the ${SANDBOX_LABEL[sandbox]} blocking network access.`,
		"  Background generation inherits the sandbox, so it cannot finish either, and this",
		"  commit is not retried later. If the sandbox is not the cause, the real error is in",
		"  .jolli/jollimemory/debug.log.",
		...fixLines(sandbox).map((line) => `  ${line}`),
	].join("\n");
}
