package ai.jolli.jollimemory.toolwindow.views

import ai.jolli.jollimemory.core.CommitSummary
import ai.jolli.jollimemory.core.ConversationTokenBreakdown
import ai.jolli.jollimemory.core.DiffStats
import ai.jolli.jollimemory.core.E2eTestScenario
import ai.jolli.jollimemory.core.LlmCallMetadata
import ai.jolli.jollimemory.core.PlanReference
import ai.jolli.jollimemory.core.TopicCategory
import ai.jolli.jollimemory.core.TopicImportance
import ai.jolli.jollimemory.core.TopicSummary
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

class SummaryMarkdownBuilderTest {

    private fun makeSummary(
        topics: List<TopicSummary> = listOf(
            TopicSummary("Test Topic", "Trigger", "Response", "Decision", category = TopicCategory.feature, importance = TopicImportance.major),
        ),
        plans: List<PlanReference>? = null,
        e2e: List<E2eTestScenario>? = null,
    ) = CommitSummary(
        commitHash = "abc1234567890",
        commitMessage = "Fix the login bug",
        commitAuthor = "Alice",
        commitDate = "2026-01-15T10:30:00Z",
        branch = "feature/login-fix",
        generatedAt = "2026-01-15T10:35:00Z",
        stats = DiffStats(3, 100, 50),
        conversationTurns = 5,
        topics = topics,
        plans = plans,
        e2eTestGuide = e2e,
    )

    @Nested
    inner class BuildMarkdown {
        @Test
        fun `includes commit message as H1`() {
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary())
            md shouldContain "# Fix the login bug"
        }

        @Test
        fun `includes properties section`() {
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary())
            md shouldContain "**Commit:**"
            md shouldContain "**Branch:**"
            md shouldContain "**Author:** Alice"
            md shouldContain "**Changes:**"
        }

        @Test
        fun `includes topic sections`() {
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary())
            md shouldContain "Test Topic"
            md shouldContain "Why This Change"
            md shouldContain "Decisions Behind the Code"
            md shouldContain "What Was Implemented"
        }

        @Test
        fun `includes footer`() {
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary())
            md shouldContain "Generated by JolliMemory"
        }

        @Test
        fun `includes plans section when plans exist`() {
            val plans = listOf(PlanReference("plan1", "My Plan", 2, "2026-01-01T00:00:00Z", "2026-01-01T00:00:00Z"))
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary(plans = plans))
            md shouldContain "## Plans"
            md shouldContain "My Plan"
        }

        @Test
        fun `includes E2E section when scenarios exist`() {
            val e2e = listOf(
                E2eTestScenario("Login test", "Have account", listOf("Open app", "Click login"), listOf("Dashboard shows")),
            )
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary(e2e = e2e))
            md shouldContain "## E2E Test"
            md shouldContain "Login test"
            md shouldContain "Open app"
        }

        @Test
        fun `includes conversations when turns greater than 0`() {
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary())
            md shouldContain "**Conversations:**"
        }

        // Token/cost "Task usage" line shared to the Jolli site — must match the VS Code
        // SummaryMarkdownBuilder output verbatim (exact counts, Sonnet-rate $) so a memory
        // reads the same whichever editor pushed it.
        @Test
        fun `includes Task usage with cost and segment split when a breakdown is present`() {
            val summary = makeSummary().copy(
                conversationTokenBreakdown = ConversationTokenBreakdown(1_000_000, 1_000_000, 1_000_000),
            )
            val md = SummaryMarkdownBuilder.buildMarkdown(summary)
            md shouldContain
                "- **Task usage:** 3,000,000 tokens · \$21.75 (1,000,000 input, 1,000,000 output, 1,000,000 cached)"
        }

        @Test
        fun `Task usage prices a breakdown-less token total at the input rate, no split`() {
            val summary = makeSummary().copy(conversationTokens = 1_000_000)
            val md = SummaryMarkdownBuilder.buildMarkdown(summary)
            md shouldContain "- **Task usage:** 1,000,000 tokens · \$3.00"
            md shouldNotContain "input, "
        }

        @Test
        fun `Task usage omitted when there are no conversation tokens`() {
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary())
            md shouldNotContain "**Task usage:**"
        }

        @Test
        fun `includes todo when present`() {
            val topics = listOf(TopicSummary("Title", "Trigger", "Response", "Decision", todo = "Follow up needed"))
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary(topics = topics))
            md shouldContain "Future Enhancements"
            md shouldContain "Follow up needed"
        }

        @Test
        fun `includes filesAffected when present`() {
            val topics = listOf(TopicSummary("Title", "Trigger", "Response", "Decision", filesAffected = listOf("src/Auth.ts", "src/Middleware.ts")))
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary(topics = topics))
            md shouldContain "FILES"
            md shouldContain "`src/Auth.ts`"
        }

        @Test
        fun `footer falls back to plain two-segment format when llm source is absent`() {
            val md = SummaryMarkdownBuilder.buildMarkdown(makeSummary())
            md shouldContain "Generated by JolliMemory"
            md shouldNotContain "via"
        }

        @Test
        fun `footer includes provider source when populated`() {
            val summary = makeSummary().copy(
                llm = LlmCallMetadata(
                    model = "claude-sonnet-4-6",
                    inputTokens = 100,
                    outputTokens = 50,
                    apiLatencyMs = 500,
                    stopReason = "end_turn",
                    source = "anthropic-config",
                ),
            )
            val md = SummaryMarkdownBuilder.buildMarkdown(summary)
            md shouldContain "via Anthropic"
        }
    }

}
