package ai.jolli.jollimemory.toolwindow.views

import ai.jolli.jollimemory.core.CommitSummary
import ai.jolli.jollimemory.core.DiffStats
import ai.jolli.jollimemory.core.E2eTestScenario
import ai.jolli.jollimemory.core.NoteFormat
import ai.jolli.jollimemory.core.NoteReference
import ai.jolli.jollimemory.core.PlanReference
import ai.jolli.jollimemory.core.TopicCategory
import ai.jolli.jollimemory.core.TopicImportance
import ai.jolli.jollimemory.core.TopicSummary
import io.kotest.matchers.ints.shouldBeGreaterThan
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

class SummaryPrMarkdownBuilderTest {

    private fun makeSummary(
        topics: List<TopicSummary> = listOf(
            TopicSummary(
                "Test Topic", "Trigger text", "Response text", "Decision text",
                category = TopicCategory.feature, importance = TopicImportance.major,
                todo = "Follow up needed", filesAffected = listOf("src/Auth.ts", "src/Middleware.ts"),
            ),
        ),
        plans: List<PlanReference>? = null,
        notes: List<NoteReference>? = null,
        e2e: List<E2eTestScenario>? = null,
        jolliDocUrl: String? = null,
    ) = CommitSummary(
        commitHash = "abc1234567890",
        commitMessage = "Fix the login bug",
        commitAuthor = "Alice",
        commitDate = "2026-01-15T10:30:00Z",
        branch = "feature/login-fix",
        generatedAt = "2026-01-15T10:35:00Z",
        stats = DiffStats(3, 100, 50),
        conversationTurns = 5,
        topics = topics,
        plans = plans,
        notes = notes,
        e2eTestGuide = e2e,
        jolliDocUrl = jolliDocUrl,
    )

    @Nested
    inner class BuildPrMarkdown {
        @Test
        fun `includes topics but not commit properties`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary())
            md shouldContain "Test Topic"
            md shouldNotContain "**Commit:**"
        }

        @Test
        fun `includes Jolli Memory URL when present`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(
                makeSummary(jolliDocUrl = "https://test.jolli.ai/articles/123")
            )
            md shouldContain "## Jolli Memory"
            md shouldContain "https://test.jolli.ai/articles/123"
        }

        @Test
        fun `includes footer`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary())
            md shouldContain "Generated by JolliMemory"
        }

        @Test
        fun `uses Topic heading instead of Summary`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary())
            md shouldContain "## Topic (1)"
            md shouldNotContain "## Summary"
        }

        @Test
        fun `uses Topics plural for multiple topics`() {
            val topics = listOf(
                TopicSummary("Topic A", "T", "R", "D"),
                TopicSummary("Topic B", "T", "R", "D"),
            )
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(topics = topics))
            md shouldContain "## Topics (2)"
        }
    }

    @Nested
    inner class DetailsStructure {
        @Test
        fun `wraps topics in details-summary-blockquote`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary())
            md shouldContain "<details>"
            md shouldContain "<summary>"
            md shouldContain "</summary>"
            md shouldContain "<blockquote>"
            md shouldContain "</blockquote>"
            md shouldContain "</details>"
        }

        @Test
        fun `includes br spacer after summary`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary())
            md shouldContain "</summary>\n<br>"
        }

        @Test
        fun `has balanced details tags`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary())
            val opens = Regex("<details>").findAll(md).count()
            val closes = Regex("</details>").findAll(md).count()
            opens shouldBe closes
            opens shouldBeGreaterThan 0
        }

        @Test
        fun `escapes title inside summary with escHtml`() {
            val topics = listOf(TopicSummary("Title <script>alert(1)</script>", "T", "R", "D"))
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(topics = topics))
            md shouldContain "&lt;script&gt;"
            md shouldNotContain "<script>"
        }
    }

    @Nested
    inner class TopicBody {
        @Test
        fun `includes all body fields`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary())
            md shouldContain "Why This Change"
            md shouldContain "Trigger text"
            md shouldContain "Decisions Behind the Code"
            md shouldContain "Decision text"
            md shouldContain "What Was Implemented"
            md shouldContain "Response text"
            md shouldContain "Future Enhancements"
            md shouldContain "Follow up needed"
            md shouldContain "FILES"
            md shouldContain "`src/Auth.ts`"
        }

        @Test
        fun `omits todo when null`() {
            val topics = listOf(TopicSummary("Title", "T", "R", "D", todo = null))
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(topics = topics))
            md shouldNotContain "Future Enhancements"
        }

        @Test
        fun `omits files when empty`() {
            val topics = listOf(TopicSummary("Title", "T", "R", "D", filesAffected = emptyList()))
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(topics = topics))
            md shouldNotContain "FILES"
        }
    }

    @Nested
    inner class EscapeGithubWrapperTags {
        @Test
        fun `escapes details tags in body content`() {
            val escaped = SummaryPrMarkdownBuilder.escapeGithubWrapperTags("before <details>inner</details> after")
            escaped shouldContain "&lt;details&gt;"
            escaped shouldContain "&lt;/details&gt;"
            escaped shouldNotContain "<details>"
        }

        @Test
        fun `escapes blockquote tags in body content`() {
            val escaped = SummaryPrMarkdownBuilder.escapeGithubWrapperTags("<blockquote>hi</blockquote>")
            escaped shouldContain "&lt;blockquote&gt;"
            escaped shouldContain "&lt;/blockquote&gt;"
        }

        @Test
        fun `escapes attribute variants like details open`() {
            val escaped = SummaryPrMarkdownBuilder.escapeGithubWrapperTags("<details open>")
            escaped shouldContain "&lt;details open&gt;"
        }

        @Test
        fun `preserves other HTML tags`() {
            val escaped = SummaryPrMarkdownBuilder.escapeGithubWrapperTags("<code>x</code> <br> <img src='a'>")
            escaped shouldContain "<code>"
            escaped shouldContain "<br>"
            escaped shouldContain "<img"
        }

        @Test
        fun `case insensitive`() {
            val escaped = SummaryPrMarkdownBuilder.escapeGithubWrapperTags("<DETAILS><BLOCKQUOTE>")
            escaped shouldContain "&lt;DETAILS&gt;"
            escaped shouldContain "&lt;BLOCKQUOTE&gt;"
        }

        @Test
        fun `sanitizes topic body content in PR output`() {
            val topics = listOf(TopicSummary("Title", "has <details>injection</details>", "R", "D"))
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(topics = topics))
            md shouldContain "&lt;details&gt;"
            // The wrapper <details> tags should still be present (unescaped)
            md shouldContain "<details>"
        }
    }

    @Nested
    inner class E2eTestSection {
        private val e2e = listOf(
            E2eTestScenario("Login test", "Have account", listOf("Open app", "Click login"), listOf("Dashboard shows")),
        )

        @Test
        fun `wraps each scenario in details`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(e2e = e2e))
            md shouldContain "## E2E Test (1)"
            md shouldContain "<details>"
            md shouldContain "<strong>1. Login test</strong>"
        }

        @Test
        fun `escapes scenario title in summary tag`() {
            val e2eXss = listOf(
                E2eTestScenario("Test <img onerror=alert(1)>", null, listOf("Step"), listOf("Result")),
            )
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(e2e = e2eXss))
            md shouldContain "&lt;img onerror=alert(1)&gt;"
            md shouldNotContain "<img onerror"
        }

        @Test
        fun `sanitizes preconditions and steps`() {
            val e2eInject = listOf(
                E2eTestScenario("Title", "<details>bad</details>", listOf("<blockquote>step"), listOf("result")),
            )
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(e2e = e2eInject))
            md shouldContain "&lt;details&gt;"
            md shouldContain "&lt;blockquote&gt;"
        }

        @Test
        fun `includes preconditions steps and expected results`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(e2e = e2e))
            md shouldContain "**Preconditions:** Have account"
            md shouldContain "1. Open app"
            md shouldContain "2. Click login"
            md shouldContain "- Dashboard shows"
        }
    }

    @Nested
    inner class PlansAndNotesSection {
        @Test
        fun `includes plans with URLs as links`() {
            val plans = listOf(
                PlanReference("p1", "My Plan", 2, "2026-01-01T00:00:00Z", "2026-01-01T00:00:00Z", jolliPlanDocUrl = "https://jolli.ai/plans/1"),
            )
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(plans = plans))
            md shouldContain "## Plans & Notes"
            md shouldContain "[My Plan](https://jolli.ai/plans/1)"
        }

        @Test
        fun `includes plans without URLs as plain text`() {
            val plans = listOf(
                PlanReference("p1", "Local Plan", 1, "2026-01-01T00:00:00Z", "2026-01-01T00:00:00Z"),
            )
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(plans = plans))
            md shouldContain "- Local Plan"
        }

        @Test
        fun `includes notes with URLs as links`() {
            val notes = listOf(
                NoteReference("n1", "My Note", NoteFormat.markdown, addedAt = "2026-01-01T00:00:00Z", updatedAt = "2026-01-01T00:00:00Z", jolliNoteDocUrl = "https://jolli.ai/notes/1"),
            )
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(notes = notes))
            md shouldContain "[My Note](https://jolli.ai/notes/1)"
        }

        @Test
        fun `shows combined count for plans and notes`() {
            val plans = listOf(PlanReference("p1", "Plan", 1, "2026-01-01T00:00:00Z", "2026-01-01T00:00:00Z"))
            val notes = listOf(NoteReference("n1", "Note", NoteFormat.markdown, addedAt = "2026-01-01T00:00:00Z", updatedAt = "2026-01-01T00:00:00Z"))
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(plans = plans, notes = notes))
            md shouldContain "## Plans & Notes (2)"
        }

        @Test
        fun `omits section when no plans or notes`() {
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary())
            md shouldNotContain "Plans & Notes"
        }
    }

    @Nested
    inner class Truncation {
        @Test
        fun `truncates topics at 65K with omission warning`() {
            // Create topics with large enough content to exceed the limit
            val bigText = "x".repeat(5000)
            val topics = (1..20).map {
                TopicSummary("Topic $it", bigText, bigText, bigText)
            }
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(topics = topics))
            md shouldContain "omitted due to GitHub PR body size limit"
        }

        @Test
        fun `singular omission message for one topic`() {
            val bigText = "x".repeat(60000)
            val topics = listOf(
                TopicSummary("Included", "short", "short", "short"),
                TopicSummary("Omitted", bigText, bigText, bigText),
            )
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(topics = topics))
            md shouldContain "1 more topic omitted"
        }

        @Test
        fun `plural omission message for multiple topics`() {
            val bigText = "x".repeat(30000)
            val topics = listOf(
                TopicSummary("Included", "short", "short", "short"),
                TopicSummary("Omitted1", bigText, bigText, bigText),
                TopicSummary("Omitted2", bigText, bigText, bigText),
            )
            val md = SummaryPrMarkdownBuilder.buildPrMarkdown(makeSummary(topics = topics))
            md shouldContain "more topics omitted"
        }
    }

    @Nested
    inner class WrapInGithubDetails {
        @Test
        fun `produces correct structure`() {
            val result = SummaryPrMarkdownBuilder.wrapInGithubDetails(
                "<strong>Title</strong>",
                listOf("", "body line"),
            )
            result shouldBe listOf(
                "<details>",
                "<summary><strong>Title</strong></summary>",
                "<br>",
                "<blockquote>",
                "",
                "body line",
                "",
                "</blockquote>",
                "</details>",
            )
        }
    }
}
