/**
 * NextraRenderer — SiteRenderer implementation for Nextra v4.
 *
 * Delegates each surface to a dedicated module: scaffolding to
 * `NextraProjectWriter`, navigation to `MetaGenerator`, build/dev to
 * `NpmRunner`, OpenAPI emission to `nextra/`. The OpenAPI side produces
 * a list of `TemplateFile`s with project-root-relative paths; this
 * class writes each one to disk under the build directory.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { generateMetaFiles } from "../MetaGenerator.js";
import { initNextraProject } from "../NextraProjectWriter.js";
import { runNpmBuild, runNpmDev, type ServerResult } from "../NpmRunner.js";
import type { OutputFilter } from "../OutputFilter.js";
import { createOutputFilter as createFilter } from "../OutputFilter.js";
import type { NpmRunResult, SidebarOverrides, SiteJson } from "../Types.js";
import { generateApiCss } from "./nextra/ApiCss.js";
import { emitNextraOpenApiFiles, generateApiComponents } from "./nextra/index.js";
import type { TemplateFile } from "./nextra/Types.js";
import type { ContentRules, OpenApiSpecInput, SiteRenderer } from "./SiteRenderer.js";

// ─── Nextra-specific constants ──────────────────────────────────────────────

const SAFE_IMPORT_PREFIXES = ["nextra", "nextra-theme-docs", "next/", "next-themes", "react"];

const PROVIDED_COMPONENTS = new Set(["Fragment", "Callout", "Cards", "Card", "FileTree", "Steps", "Tabs", "Tab"]);

const PAGE_COUNT_PATTERN = /Generating static pages.*?(\d+)\/(\d+)/s;

/**
 * Pack manifest defaults — kept in sync with `themes/<pack>/Manifest.ts`.
 * Hardcoded here because importing the manifests from inside `renderer/`
 * would invert the dependency direction (renderer should not depend on
 * pack-specific modules; ApiCss is pack-agnostic).
 */
const FORGE_DEFAULT_HUE = 228;
const ATLAS_DEFAULT_HUE = 200;

/**
 * Resolves the accent hue passed to `generateApiCss`. `theme.primaryHue`
 * wins when set; otherwise we fall back to a pack-aware default so the
 * API surface visually matches the pack the customer picked. Returning
 * `undefined` lets `generateApiCss` apply its own internal default (220).
 */
function resolveApiAccentHue(config: SiteJson): number | undefined {
	if (typeof config.theme?.primaryHue === "number") {
		return config.theme.primaryHue;
	}
	switch (config.theme?.pack) {
		case "forge":
			return FORGE_DEFAULT_HUE;
		case "atlas":
			return ATLAS_DEFAULT_HUE;
		default:
			return undefined;
	}
}

// ─── NextraRenderer ─────────────────────────────────────────────────────────

export class NextraRenderer implements SiteRenderer {
	readonly name = "nextra";

	async initProject(
		buildDir: string,
		config: SiteJson,
		options: { staticExport?: boolean },
	): Promise<{ isNew: boolean }> {
		const result = await initNextraProject(buildDir, config, options);
		// Components are scaffold — every page generated by `renderOpenApiSpecs`
		// imports them via the `@/components/api/...` alias defined in the
		// tsconfig that `initNextraProject` just wrote, so they have to land
		// before any MDX shim does. Writing them once here also avoids
		// rewriting nine files on every render-loop call. The API stylesheet
		// is also scaffold — `app/layout.tsx` imports it unconditionally.
		//
		// `accentHue` flows from `theme.primaryHue` so the API method/status
		// pills match the rest of the pack. When the user picks Forge but
		// doesn't override the hue, fall back to Forge's manifest default
		// (228) so the API surface inherits the pack's identity instead of
		// the unrelated `generateApiCss` fallback (220).
		const accentHue = resolveApiAccentHue(config);
		await this.writeFiles(buildDir, [...generateApiComponents(), generateApiCss({ accentHue })]);

		return result;
	}

	getCacheDirs(buildDir: string): string[] {
		return [join(buildDir, ".next")];
	}

	async generateNavigation(contentDir: string, sidebar?: SidebarOverrides): Promise<void> {
		await generateMetaFiles(contentDir, sidebar);
	}

	/**
	 * Writes the Nextra OpenAPI emitter's per-spec output to disk:
	 *   - overview MDX, `_refs.ts`, per-operation MDX shim + JSON sidecar,
	 *     and `_meta.ts` for the spec folder + each tag folder.
	 *
	 * The 9 `components/api/*` files are NOT written here — they're
	 * scaffold and were written once by `initProject` when the build
	 * directory was set up.
	 *
	 * `publicDir` is unused — the rich pipeline does not ship the raw spec
	 * to the browser; the try-it widget builds requests from the JSON
	 * sidecar instead.
	 */
	async renderOpenApiSpecs(contentDir: string, _publicDir: string, specs: OpenApiSpecInput[]): Promise<void> {
		// `contentDir` is `<buildDir>/content/`; the emitter's `path` field is
		// project-root-relative (e.g. `content/...`), so we resolve each file
		// against the parent of `contentDir`.
		await this.writeFiles(dirname(contentDir), emitNextraOpenApiFiles(specs));
	}

	/**
	 * Writes a list of `TemplateFile`s under `buildDir`. Each `path` is
	 * project-root-relative; parent directories are created as needed and
	 * existing files are overwritten.
	 */
	private async writeFiles(buildDir: string, files: TemplateFile[]): Promise<void> {
		for (const file of files) {
			const fullPath = join(buildDir, file.path);
			await mkdir(dirname(fullPath), { recursive: true });
			await writeFile(fullPath, file.content, "utf-8");
		}
	}

	getContentRules(): ContentRules {
		return {
			safeImportPrefixes: SAFE_IMPORT_PREFIXES,
			providedComponents: PROVIDED_COMPONENTS,
		};
	}

	async runBuild(buildDir: string): Promise<NpmRunResult> {
		return runNpmBuild(buildDir);
	}

	async runDev(buildDir: string, verbose?: boolean): Promise<ServerResult> {
		return runNpmDev(buildDir, verbose);
	}

	createOutputFilter(verbose: boolean): OutputFilter {
		return createFilter(verbose);
	}

	extractPageCount(buildOutput: string): number | undefined {
		const match = buildOutput.match(PAGE_COUNT_PATTERN);
		return match ? Number.parseInt(match[2], 10) : undefined;
	}
}
