package ai.jolli.jollimemory.core

/**
 * WikiMarkdownBuilder — pure renderers for the topic-KB wiki layer at
 * `<kbRoot>/_wiki/`. No fs, no LLM, no storage — callers wire to disk.
 *
 * Kotlin port of `cli/src/core/WikiMarkdownBuilder.ts`. Output must stay
 * byte-identical with the TS renderer: the visible `.md` layer lives in the
 * synced Memory Bank folder, so any drift causes cross-tool conflicts.
 */

/**
 * A compiled topic ready for rendering. Kotlin analog of the TS `CompiledTopic`.
 *
 * @property stableSlug lowercase-kebab slug encoding the topic's concept (stable
 *   across re-compiles so the derived `_wiki/topic--<stableSlug>.md` persists).
 */
data class CompiledTopic(
    val title: String,
    val stableSlug: String,
    val content: String,
    val relatedBranches: List<String>? = null,
    val keyDecisions: List<String>? = null,
    val sourceCommits: List<String> = emptyList(),
)

/**
 * Caller-supplied context: how to render links pointing OUT of the wiki tree.
 * Source commits live under per-branch folders next to `_wiki/`; the visible
 * markdown filename includes the commit-message slug, which only the caller can
 * resolve (it lives in the manifest / branches mapping). When a commit's visible
 * filename can't be resolved, the resolver returns null and a non-link literal
 * is used instead.
 */
data class WikiRenderContext(
    /** Repo display name (e.g. "jolliai"); only used for the `_index.md` H1. */
    val repoName: String,
    /**
     * Short commit hash (8-char hex) → visible-md path **relative to `<kbRoot>/_wiki/`**,
     * or null when no visible summary exists. Expected shape: `../<branchFolder>/summary--<slug>-<hash8>.md`.
     */
    val resolveCommitVisiblePath: (commitHash8: String) -> String?,
    /** Branch name → visible branch folder name, or null when unknown. */
    val resolveBranchFolder: (branch: String) -> String?,
    /** Short commit hash (8-char) → commit message, for link display text. */
    val resolveCommitMessage: (commitHash8: String) -> String?,
)

private const val GENERATED_BANNER =
    "<!-- Generated by Jolli Memory · do not edit — regenerated on every merge -->"

/**
 * Shape-agnostic topic render: takes branches + lastUpdatedAt directly so
 * topic-KB pages render without a MergedKnowledge container.
 */
fun renderTopicImpl(
    topic: CompiledTopic,
    branches: List<String>,
    lastUpdatedAt: String,
    ctx: WikiRenderContext,
): String {
    val lines = mutableListOf<String>()
    lines.add("# ${topic.title}")
    lines.add("")
    lines.add(GENERATED_BANNER)
    lines.add("")
    lines.add("> **Source branches:** ${branches.joinToString(", ")}")
    lines.add("> **Merged:** $lastUpdatedAt")
    lines.add("> **Topic slug:** `${topic.stableSlug}` (stable across re-merges)")
    lines.add("")
    lines.add(topic.content.trim())
    lines.add("")

    val keyDecisions = topic.keyDecisions
    if (!keyDecisions.isNullOrEmpty()) {
        lines.add("## Key Decisions")
        lines.add("")
        for (decision in keyDecisions) {
            lines.add("- $decision")
        }
        lines.add("")
    }

    if (topic.sourceCommits.isNotEmpty()) {
        lines.add("## Source Commits")
        lines.add("")
        for (commitHash in topic.sourceCommits) {
            val hash8 = commitHash.take(8)
            val path = ctx.resolveCommitVisiblePath(hash8)
            val message = ctx.resolveCommitMessage(hash8)
            // Standard Markdown relative link: clickable in editors/GitHub, resolved
            // by Obsidian. When the visible MD isn't on disk (orphan-only / unknown
            // hash), drop the link target and just show the hash (+ message).
            if (path != null && message != null) {
                lines.add("- ${mdLink(hash8, stripLeadingDotSlash(path))} — $message")
            } else if (message != null) {
                lines.add("- `$hash8` — $message")
            } else {
                lines.add("- `$hash8`")
            }
        }
        lines.add("")
    }

    val relatedBranches = topic.relatedBranches
    if (!relatedBranches.isNullOrEmpty()) {
        lines.add("## Related Branches")
        lines.add("")
        for (branch in relatedBranches) {
            val folder = ctx.resolveBranchFolder(branch)
            if (folder != null) {
                lines.add("- ${mdLink(branch, "../$folder/")}")
            } else {
                lines.add("- `$branch`")
            }
        }
        lines.add("")
    }

    return lines.joinToString("\n")
}

/**
 * Adapts a topic-KB page to the [CompiledTopic] shape the renderer expects.
 * Only summary-type sourceRefs are commit hashes.
 */
fun topicPageToCompiledTopic(page: TopicPage): CompiledTopic {
    return CompiledTopic(
        title = page.title,
        stableSlug = page.stableSlug,
        content = page.content,
        relatedBranches = if (page.relatedBranches.isNotEmpty()) page.relatedBranches.toList() else null,
        sourceCommits = page.sourceRefs.filter { it.type == SourceType.SUMMARY }.map { it.id },
    )
}

/**
 * Renders a topic-KB index page from a flat list of compiled topics.
 * Shape-agnostic: takes topics + repoName directly.
 */
fun renderTopicKBIndex(topics: List<CompiledTopic>, ctx: WikiRenderContext): String {
    val lines = mutableListOf<String>()
    lines.add("# ${ctx.repoName} · Knowledge Wiki")
    lines.add("")
    lines.add(GENERATED_BANNER)
    lines.add("")
    lines.add("> **${topics.size} topics** in the knowledge base")
    lines.add("")

    if (topics.isNotEmpty()) {
        lines.add("## Topics")
        lines.add("")
        for (topic in topics) {
            lines.add("- ${mdLink(topic.title, "topic--${topic.stableSlug}.md")}")
        }
        lines.add("")
    }

    return lines.joinToString("\n")
}

private fun stripLeadingDotSlash(path: String): String =
    if (path.startsWith("./")) path.substring(2) else path

/**
 * Standard Markdown link `[label](target)`. Escapes brackets/backslash in the
 * label and percent-encodes the few characters in the target that would
 * otherwise close the `(...)` destination early. Deliberately NOT Obsidian
 * `[[wikilinks]]` (those render as plain text outside Obsidian).
 *
 * The chained replaces are equivalent to the TS single-pass regex
 * `/[\\[\]]/g → \$&` because backslash is escaped first, so brackets escaped
 * afterwards are not double-escaped.
 */
private fun mdLink(label: String, target: String): String {
    val safeLabel = label
        .replace("\\", "\\\\")
        .replace("[", "\\[")
        .replace("]", "\\]")
    val safeTarget = target
        .replace(" ", "%20")
        .replace("(", "%28")
        .replace(")", "%29")
    return "[$safeLabel]($safeTarget)"
}
